Uniswap/smart-order-router

package-lock.json, package.json
- **What kind of change does this PR introduce?** bug fix
- **What is the current behavior?** `prettier-plugin-organize-imports` is automatically added to every project with a dependency on `smart-order-router`
- **What is the new behavior (if this is a feature change)?** moved to dev dependency
- 
=> fix: move prettier-plugin-organize-imports and sinon to dev dependencies

.eslintrc.json, src/routers/alpha-router/functions/best-swap-route.ts
Import modules for mnemonist to avoid importing the entire library. This should offer significant size savings (~15kb gzipped).
=> fix: tree-shake mnemonist

CHANGELOG.md, bin/cli, package.json, src/providers/swap-router-provider.ts, src/providers/token-provider.ts, src/providers/v2/pool-provider.ts, src/providers/v3/pool-provider.ts, tsconfig.json, tsconfig.module.json, tsconfig.oclif.json
Reduces the exported package size from 3.7M to 1.4M
- Imports types explicitly to allow for tree-shaking, instead of from barrel files
- _Reduces package size from 3.7M to 1.5M_
- Splits the cli tsconfig to avoid including those files in the exported package (cli is now dev-only)
- Updates the cli file to always use ts-node
- _Reduces package size from 1.5M to 1.4M_
=> fix: split tsconfig to reduce package size

src/providers/v3/subgraph-provider.ts
Found this to be the proper Optimism graph link. info site uses this one, I'll be honest couldn't get it to build in my computer, but the link should be updated to the new one.
same link to the one just merged in uniswap/interface that I authored.
=> Update Optimism Graph link

src/routers/alpha-router/gas-models/v2/v2-heuristic-gas-model.ts
Testing here vs. tenderly. (green is underestimate compared to simulation, red is over)
Proposal:
- Increase the V2 base swap fee by 20,000 from 115,000 to 135,000
- Increase the V2 COST_PER_HOP by 30,000 from 20,000 to 50,000
This should bring our heuristic estimates within 5-10% of the actual gas usage (as reported by tenderly) which is much better than currently where we are under by about 30-40%.  However, we'd still be underestimating.
Since it looks like weth-uni is over by 18%, I'm more inclined to keep this update conservative, curious what thoughts are.
=> Bump v2 heuristic gas constants

src/providers/v2/static-subgraph-provider.ts, src/providers/v2/subgraph-provider.ts, src/routers/alpha-router/functions/get-candidate-pools.ts, test/test-util/mock-data.ts
Getting the `reserveUSD` data point returned from the V2 subgraph will allow us to add heuristics for mixed Route selection. Namely, we can compare this USD value to the `tvlUSD` value returned for v3 pools.
Going to land this and update routing-api to begin saving the new information into cloudflare.
=> Add reserveUSD to graphql query for v2 subgraph

README.md, cli/commands/quote.ts, src/util/chains.ts
fixes quoting with the native currency string in the CLI
=> should be able to quote in native currency string

src/providers/on-chain-quote-provider.ts, src/routers/router.ts, src/util/routes.ts
Few notes:
- Sara initially suggested that we use the wrapped `IRoute` instead of the SDK routes in SOR to get access to the `protocol` key and the abstracted `pools` and `path` keys.
- I tried that out, importing the `IRoute` classes and wrapping it around the new SDK routes that we create, but it added a lot of complexity to the code that I didn't really think was worth it. Namely, in computing routes and the tests.
- So since the initial goal was to remove the `instanceOf` checks against `V3Route` and `MixedRoute`, I added a protocol key to each class in SOR that we can use to differentiate with.
However I think there's merit in porting over the SOR to use the `IRoutes` entirely from router-sdk, but it's a change that I think can happen after launch
=> feat -> feat Add protocol flag to SOR version of SDK routes

cli/base-command.ts, cli/commands/quote.ts, package-lock.json, src/providers/on-chain-quote-provider.ts, src/routers/alpha-router/alpha-router.ts, src/routers/alpha-router/functions/best-swap-route.ts, src/routers/legacy-router/legacy-router.ts, test/integ/routers/alpha-router/alpha-router.integration.test.ts, test/unit/routers/alpha-router/alpha-router.test.ts
Feature branch for implementing:
- Using one instance of `OnChainQuoteProvider` for V3, MixedRoute, and V2 quotes.
- Removing the `disableMixedRoutesConsideration` flag and adjusting the logic for protocol queries
- Adding `forceMixedRoutes`
- Adding various tests for `getMixedRouteQuotes()` in alpha-router
TODO:
- need to test that we can call the onChainQuoteProvider and get on chain quotes for V2 exactIn routes
=> feat->feat Refactor on chain quote provider

package.json
Fixes the issues users are having in #58 - the issue occurs if they have v4 not v3 of JSBI. Given JSBI is not a direct dependency of this repo, I'm adding the version that we use as a peer dependency.
=> Add peer dependency to fix JSBI issue

src/providers/v2/subgraph-provider.ts
- **What kind of change does this PR introduce?** Feature to set pageSize for v2SubgraphProvider
- **What is the current behavior?** Uses pageSize = 1000
- **What is the new behavior (if this is a feature change)?**. Uses whatever pageSize is passed, 1000 by default
- **Other information**: This is to try to work around this issue: https://github.com/Uniswap/v2-subgraph/issues/78 
By reducing page size we may be able to get the subgraph query to work more reliably
=> Added param for page size for v2 subgraph provider

src/providers/v3/subgraph-provider.ts
This is a patch for an issue reported by the research team. Longer term fix is in the Subgraph, but due to resourcing unlikely to get fixed any time soon.
The research team reported that [this pool](https://info.uniswap.org/#/pools/0xd9961ea871a52456a5ad4bccb981d40ed7fdb813) is not showing up in the interface. 
I took a quick look and found it is being [filtered out of the V3 Subgraph query](https://github.com/Uniswap/smart-order-router/blob/main/src/providers/v3/subgraph-provider.ts#L206) because the subgraph says its liquidity == 0. 
Its liquidity is actually not 0 as [can be seen here](https://etherscan.io/address/0xd9961ea871a52456a5ad4bccb981d40ed7fdb813#readContract#F5), so there is an issue with …
=> Include V3 pools from subgraph where there is a small quantity of ETH locked up

cli/commands/quote-to-ratio.ts
I was trying to run the CLI but was running into the following error while calling `./bin/cli`
```
(node:361995) TSError Plugin: @uniswap/smart-order-router: ⨯ Unable to compile TypeScript:
cli/commands/quote-to-ratio.ts:120:9 - error TS2741: Property 'type' is missing in type '{ deadline: number; recipient: string; slippageTolerance: Percent; }' but required in type 'SwapOptionsSwapRouter02'.
120         swapOptions: {
~~~~~~~~~~~
src/routers/router.ts:139:3
139   type: SwapType.SWAP_ROUTER_02;
~~~~
'type' is declared here.
```
It looks like the call signature for the swapOption args is a bit different.
This fixed that particular bug, but there's a series of other mismatched constructor issues reported when calling `./bin/cli`
Please let me know if I'm missing something.
=> fixed swapOptions missing in CLI

src/routers/alpha-router/alpha-router.ts, src/routers/alpha-router/index.ts, src/routers/alpha-router/quoters/base-quoter.ts, src/routers/alpha-router/quoters/index.ts, src/routers/alpha-router/quoters/mixed-quoter.ts, src/routers/alpha-router/quoters/model/index.ts, src/routers/alpha-router/quoters/model/results/get-quotes-result.ts, src/routers/alpha-router/quoters/model/results/get-routes-result.ts, src/routers/alpha-router/quoters/model/results/index.ts, src/routers/alpha-router/quoters/quoter.ts, src/routers/alpha-router/quoters/v2-quoter.ts, src/routers/alpha-router/quoters/v3-quoter.ts
- Create Quoters and encapsulate business logic
- remove unecessary imports
- build v2 gasmodel inside the quoter
This is a refactor of code, it encapsulates the logic of fetching routes and quoting per protocol into their own classes with a shared interface
Currently all the quoting logic is inside AlphaRouter, it is a little hard to read the code since it is not encapsulated
New abstraction, interface and encapsulation. It makes the code more readable and easier to work with
Tests are currently being delegated to the tests in AlphaRouter …
=> Refactor and create Quoter models

cli/base-command.ts, src/routers/alpha-router/functions/get-candidate-pools.ts
This is a bug fix.
We were previously only taking the TopN pools of *all* second hop tokens, which could end up being all pools for the same second hop token, It would return an incomplete exploration of the second hops.
With this change we will now take the topN pools for each second hop, it will potentially result in more routes to be explored, but it will explore all routes that require a second hop.
Routing Configuration might need to be adjusted based on this change
=> Take the TopN for each second hop

cli/base-command.ts, cli/commands/quote.ts, src/routers/alpha-router/alpha-router.ts, src/routers/alpha-router/functions/get-candidate-pools.ts
feature
Currently we indiscriminately select the topN for all second hops
This feature allows us to specify more granularity for second hops given a token address
=> Allow more granularity when selection topN for second hops

src/routers/alpha-router/alpha-router.ts
bug fix
possible versioning mismatch which causes this check to fail when it shouldn't. instead we should use the `isProvider` check on `JsonRpcProvider`
Use the `JsonRpcProvider` built-in function for checking the type.
=> fix: remove instanceof usage for provider

src/providers/caching/route/model/cached-route.ts, src/providers/caching/route/model/cached-routes.ts, test/unit/providers/caching/route/model/cached-route.test.ts
Bug Fix
Currently the constructor of CachedRoutes is private and it is not using named arguments.
making the constructor public is necessary for the marshalling step in routing-api and the named arguments are mostly for readability.
we likely have to update version 3.8.1, 3.9.1 and 3.10.1
=> Changes to CachedRoutes and CachedRoute in preparation for usage in routing-api

src/routers/alpha-router/gas-models/mixedRoute/mixed-route-heuristic-gas-model.ts
Sometimes mixed routes will estimate 0 for `gasInTermsOfQuoteToken` because while the V3Pool does exist, it has 0 liquidity and thus the resulting gas cost in terms of quote token is 0, causing the AutoRouter to incorrectly choose the mixed route over more viable V2 or V3 ones.
There's still the issue of mixed routes preferring the V3 pool in all other cases compared to the V2 pool, but it's difficult to determine which pool is "better" at runtime.
The following quote on main should select a Mixed route with 0 as the `Gas Used Quote Token: XX`, but on this branch should be well defined.
```
./bin/cli quote --tokenIn c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 --tokenOut 0xe57402125e1fae01abb1d30d1efbec68a7ee5bd1 --amount 0.07 --exactIn --recipient 0xAb5801a7D398351b8bE11C439e05C5B3259aeC9B …
```
=> Fix nativePool selection for mixed routes

src/providers/caching/route/model/cached-route.ts, src/routers/alpha-router/alpha-router.ts
Bug Fix
Currently, if there's a V2Route in Cache, the reserves are also cached, and those reserves are being fetched from a subgraph which might have not indexed the correct reserves yet.
If we have v2Routes in the CachedRoute, then we will recompute the routes for V2. This is okay for now since the latency of v2 is way lower than v3, but could be improved in the future by having a way to refetch the data for the pool directly.
=> For CachedRoutes, if we have a V2 Route cached, we need to reload the pool reserves

src/providers/token-provider.ts, src/providers/v3/static-subgraph-provider.ts
Bug Fix
Currently pairs against OP and ARB are not being used in the PoolProvider because there's no subgraph on those chains and we aren't matching against these tokens
Tokens are now added and we will look for pairs using OP or ARB
=> Add ARB and OP to their respective chains for use in the PoolProviders

src/routers/alpha-router/alpha-router.ts
Feature/Bug Fix.
Currently we only fetch a quote for the specific percent that the route was cached for, however it's possible that block data is updated and the routes have changed. In such a case it is a good idea to fetch the different percents for all routes to be able to give some margin of error to the caching layer
We will now fetch the different percents for all routes that have been cached
=> Update how we fetch percents and amounts for cached routes

src/providers/token-provider.ts, test/integ/routers/alpha-router/alpha-router.integration.test.ts
Bug Fix
Currently if the symbol method is a bytes32 instead of string, we would crash
We don't crash anymore
Tested manually with `./bin/cli quote --tokenIn 0x0d88ed6e74bbfd96b831231638b66c05571e824f --tokenOut 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 --amount 1 --exactIn --chainId 1` and got a 200 response with a real quote.
Also added an integration test.
=> BugFix: When symbol is bytes32 we are crashing, this fixes it and handles it gracefully

src/providers/token-provider.ts
BugFix
Bytes32 strings are displayed with the raw bytes data
We parse the string
=> If symbol comes from bytes32 function, we need to parse it

src/providers/v3/static-subgraph-provider.ts
Bug fix
`StaticV3SubgraphProvider` currently doesn't get the block number from the alpha router to get the pools.
`StaticV3SubgraphProvider` gets the block number from the alpha router, and passes down to the downstream pool provider (concrete instance of `IV3PoolProvider`) to get the pools.
This is to complement the routing-api pr [211](https://github.com/Uniswap/routing-api/pull/211). Dynamo caching pool provider will always be cache miss until we pass down the block number.
=> [ROUTE-9] pass down block number to v3 static subgraph provider

src/routers/alpha-router/alpha-router.ts
Infura has fixed gas issues for Optimism as of yesterday. Reverting on-call fix for optimism since things are back to normal. 
Local test run worked:
=> fix: revert OP multicall chunk size back to normal

src/providers/v3/caching-pool-provider.ts
Enhancement
We don't know the cache hit/miss ratio for the existing v3 caching pool provider.
We will see cache hit/miss ratio for the existing v3 caching pool provider. I tested this in routing-api personal cdk stack (via local tarball [method](https://github.com/Uniswap/routing-api/compare/jsy1218/explore-sor-local-tarball?expand=1)). I can see in-memory cache hit/miss metrics getting exported:
The high hit rate has caught my attention. Originally we thought that the hit rate might be low in prod, so we want to add the dynamo caching. …
=> add v3 in-memory caching pool hit miss metrics

src/providers/eth-estimate-gas-provider.ts, src/providers/tenderly-simulation-provider.ts, src/routers/alpha-router/alpha-router.ts, src/routers/alpha-router/gas-models/gas-model.ts, src/routers/alpha-router/gas-models/mixedRoute/mixed-route-heuristic-gas-model.ts, src/routers/alpha-router/gas-models/v3/v3-heuristic-gas-model.ts, src/util/gas-factory-helpers.ts, test/unit/routers/alpha-router/alpha-router.test.ts
We want to pass the block number down to the v3 pool provider on the TVL heuristics path on v3, so that [DynamoCachingV3PoolProps](https://github.com/Uniswap/routing-api/blob/main/lib/handlers/pools/pool-caching/v3/cache-dynamo-pool.ts) can actually cache the per-block pool depending on which token pairs.
In prod, each hour we have about 100k dynamo pool cache misses due to no block number:
This is quite a large number, considering we only enabled 1% shadow sampling into dynamo pool cache. This means if we would've enabled 100% sampling, then each hour there would've been 100M dynamo pool cache misses due to no block number. …
=> [fix] [ROUTE-9] pass block number to v3 get liquidity TVL

src/routers/alpha-router/functions/get-candidate-pools.ts, test/unit/routers/alpha-router/functions/get-candidate-pools.test.ts
Bug fix
With the left over item from https://github.com/Uniswap/smart-order-router/pull/253, we expect to still see some Dynamo pool caching miss due to the missing block number:
> I think we want to pass down the block number to candidate pools in a separate PR to see the cache hit improvement incrementally.
We first ran the integ-test in routing-api before making this change. We saw some cache miss due to missing block number as expected. Then we make this PR change, and locally test via [tarball](https://github.com/Uniswap/routing-api/compare/main...jsy1218/explor …
=> [ROUTE-9] Pass down block number to v3 candidate pool

src/providers/v2/pool-provider.ts
Enhancement
We don't know what is the v2 Pool Provider RPC call volume. From [routing-api](https://github.com/Uniswap/routing-api), we don't cache pool at all in v2, and instead we will always make a RPC call. In specific, this is in [inject-sor.ts](https://github.com/Uniswap/routing-api/blob/main/lib/handlers/injector-sor.ts#LL255C1-L256C1). 
We will start exporting v2 pool provider RPC call metric, so we have an idea of the call volume. Depending on the call volume, we can then decide if we want to proceed to make the V2 dynamo caching pool as parity to v3 dynamo …
=> export v2 rpc call volume metric

src/providers/v3/subgraph-provider.ts, src/util/chains.ts
adding items I missed in last PRs for AVAX support. discovered due to routing-api integration tests failing for avax
=> fix: add subgraph & cachedNativeCurrency method for avax

package-lock.json, src/providers/token-provider.ts, src/routers/alpha-router/alpha-router.ts, src/routers/alpha-router/gas-models/v3/gas-costs.ts, src/routers/alpha-router/gas-models/v3/v3-heuristic-gas-model.ts
Two modifications to the algorithm we use for computing gas estimates: 
1/ increase estimate for single hop swaps.
2/ add a custom overhead for certain known expensive to transfer tokens (AAVE and LDO)
Also reduces cache length for the gas price from 15s -> 7s
Gas prices are cached for 15s
There is no functionality for applying gas overheads based on the tokens being swapped
There is no gas overhead applied for single hop swaps
Cache gas for 7s
Apply a 15k overhead to the route if it has 1 hop
Add a 150k overhead for routes that involve AAVE or LDO
- **Other …
=> Adjust gas estimates for single hop, and reduce cache length

test/integ/routers/alpha-router/alpha-router.integration.test.ts
Test fix
Currently the const is evaluated at declaration time, but there might be some chains that are under development for which there are no mappings yet.
Now the const is lzily evaluated and we can declare it as we need. It will not be evaluated until we actually have to call that chain.
=> Lazy evaluation of test const

package-lock.json, package.json
Release 3.15.1
This release contains an update of the subgraph url to point to the latest version rather than a specific version for BASE
=> Release version 3.15.1

package-lock.json, package.json
Bug fix
We are on the older version of universal-router-sdk that doesn't support BASE yet.
We bump universal-router-sdk to version 1.5.7 that supports BASE.
I noticed our sor integ-tests filtered out the BASE, so that we didn't catch this. https://github.com/Uniswap/smart-order-router/blob/main/test/integ/routers/alpha-router/alpha-router.integration.test.ts#L2598
=> fix: bump ur sdk in sor to support BASE

test/integ/routers/alpha-router/alpha-router.integration.test.ts
Testing coverage
We filter out avax and base networks during integ-test
We un-filter out avax and base networks during integ-test
The amount of test failures don't change https://app.warp.dev/block/y16oMODWytFQFglttt9mkN. We will follow up with another integ-test fix due to the UR address upgrade to v1.2
=> fix: unfilter avax and base network integ-test

src/util/gas-factory-helpers.ts, test/test-util/mock-data.ts, test/unit/routers/alpha-router/util/gas-factory-helpers.test.ts
TLDR: there is a bug in how the pool with the highest liquidity is chosen amount v3 pools. This was causing us to use a very illiquid 1inch<>WETH pool for quoting gas prices, leading to a severely low gas estimation. 
This fixes it, though we should add a task to refactor this logic / design
=> fix: buggy max by sorting for liquidity among pools

test/integ/routers/alpha-router/alpha-router.integration.test.ts
Bug fix
All the hardfork integ-tests are failing. See the warp link under https://github.com/Uniswap/smart-order-router/pull/299.
We use a later block, that has the universal router v1.2 deploy address. And for WETH whale, we need to change the address where the new address has at least 4000 WETH with the newly hard-coded block.
For some reason, base mainnet integ-tests start failing with insufficient gas limits https://app.warp.dev/block/tCQ8sTuuw42vtQjttnDlAE. But we can follow-up in a linear ticket.
See more context on why this fix in the …
=> fix: hardhat fork in the integ-tests

src/routers/alpha-router/alpha-router.ts
Bug fix
Base mainnet integ-tests are failing due to gas https://app.warp.dev/block/tCQ8sTuuw42vtQjttnDlAE.
Reduce Base multichunk so swap integ-tests aren't failing anymore. https://app.warp.dev/block/qBFFXAPgnzIsqjX4atI7Pd
Not sure when we started to see BASE gas failures. But it might impact prod, as we started seeing the gas error [metrics](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#metricsV2?graph=~(metrics~(~(~'Uniswap~'QuoteOutOfGasExceptionRetry~'Service~'RoutingAPI))~view~'timeSeries~stacked~false~region …
=> fix base multicall multichunk for gas

src/providers/caching/route/model/cached-routes.ts, src/providers/caching/route/route-caching-provider.ts, src/routers/alpha-router/alpha-router.ts, test/unit/providers/caching/route/model/cached-routes.test.ts
feature
this is a preparation for optimistic quotes, by creating a config `optimisticCachedRoutes` which allow the RoutingAPI to specify if they are requesting an optimistic route.
Optimistic routes are defined as using the routes from cache for previous blocks to get quotes and find the best one among those routes.
In this preparation what we are doing is that we will only respect the `blocksToLive` setting if the quote is optimistic, otherwise the cached route expires with a new block.
This will allow us to control whats the maximum number of blocks we can look back to prepare a quote.
=> Optimistic Quotes preparation

src/routers/alpha-router/quoters/base-quoter.ts, src/routers/alpha-router/quoters/mixed-quoter.ts, src/routers/alpha-router/quoters/v2-quoter.ts, src/routers/alpha-router/quoters/v3-quoter.ts
Add latency instrumentation
We don't know the overall per-protocol version quotes latencies.
We will measure the overall per-protocol version quotes latencies.
The latencies breakdown we have might miss something. In order to do better fast quote analysis, we need to see the per-protocol overall latencies.
Tested in quoting-api via https://github.com/Uniswap/routing-api/compare/main...jsy1218/explore-sor-local-tarball:
=> Chore: measure per protocol version getRoutesThenQuotes and getQuotes latencies

src/routers/alpha-router/alpha-router.ts, src/routers/alpha-router/quoters/base-quoter.ts, src/routers/alpha-router/quoters/mixed-quoter.ts, src/routers/alpha-router/quoters/v2-quoter.ts, src/routers/alpha-router/quoters/v3-quoter.ts
Add per-protocol and cached vs non-cached latencies and request count instrumentation
With https://github.com/Uniswap/smart-order-router/pull/316, we did gain a bit of insights on the per-protocol `getRoutesThenQuotes` latencies breakdown. However this alone is not good enough for us to see where we can most effectively shave off the fast quote latencies. This is because the metrics being added mostly correspond to the non-cached routes getting routes and quotes path. With cached routes, we want to understand the request count distribution of cached routes vs. non-cached routes, and then within each one, we then want to …
=> Measure per-protocol quote latencies and request counts for both cached routes and non-cached routes

src/providers/provider.ts, src/routers/alpha-router/alpha-router.ts, src/routers/alpha-router/functions/get-candidate-pools.ts, src/routers/alpha-router/gas-models/gas-model.ts, src/routers/alpha-router/gas-models/mixedRoute/mixed-route-heuristic-gas-model.ts, src/routers/alpha-router/gas-models/v2/v2-heuristic-gas-model.ts, src/util/gas-factory-helpers.ts
Debug
We don't have an easy way to know whether adding caching on top of v2 pool provider will help the E2E quote latencies easily
We add a debugRouting param as part of the alpha router config, so that we can easily add the hacky caching pool provider on the routing-api side.
This PR is meant to be very short-term hack. We may revert after we have collected enough datapoints.
=> add debug routing config as part of alpha router config

src/routers/alpha-router/functions/get-candidate-pools.ts
Perf fix
`getMixedRouteCandidatePool` sequentially calls `getV3CandidatePools` and `getV2CandidatePools`. Speaking from the latencies instrumentation perspective (see internal dashboard QuoterLatencies), MixedSubgraphPoolsLoad = V3SubgraphPoolsLoad + V3PoolsFilterLoad + V3PoolsLoad + V2SubgraphPoolsLoad + V2PoolsFilterLoad + V2PoolsLoad. 
We are changing the behavior to make it MixedSubgraphPoolsLoad = max(V3SubgraphPoolsLoad + V3PoolsFilterLoad + V3PoolsLoad , V2SubgraphPoolsLoad + V2PoolsFilterLoad + V2PoolsLoad)
@mikeki is working on a …
=> parallelize v2 and v3 get candidate pools in mixed

test/integ/routers/alpha-router/alpha-router.integration.test.ts
integ-test coverage enhancement
Adding ETH -> UNI using `mixed` protocol, that should force to use V2. The test should pass against main branch.
I noticed during local testing, that with https://github.com/Uniswap/smart-order-router/pull/331, mixed route doesn't always find the route. I wrote this test to consistently repro the no swap route for https://github.com/Uniswap/smart-order-router/pull/331, and we can further QA before checking in.
=> mixed route eth -> uni test that repro smarter pool filter mixed route failure

src/routers/alpha-router/functions/get-candidate-pools.ts
bug fix
we were missing this heuristic from the refactor
the heuristic is back in
=> TopNWithEachBase heuristic

src/routers/alpha-router/functions/get-candidate-pools.ts
This is a backup plan in case the latest deploy doesn't work as we expect, we would revert the v3 heruistic changes to get the latency back to normal levels
=> Revert V3 Candidate Pool Selection

src/routers/alpha-router/functions/get-candidate-pools.ts
bug fix
currently accidentally we are adding the pool to the wrong heuristic container
fixed the issue
=> Fixing adding to TopByBaseWithTokenOut

test/integ/routers/alpha-router/alpha-router.integration.test.ts
Testing coverage
No OP mainnet integ-test coverage
Have some OP mainnet integ-test coverage
With so many changes in the last couple days, it's good to re-enable the OP mainnet coverage, just in case we have more quick changes coming up.
I already ran on local to see that op mainnet test passes: https://app.warp.dev/block/IOLIltVU02GoxPqYHXQkZc
=> re-enable op mainnet integ-test

src/routers/alpha-router/alpha-router.ts
Debug routing logging
In prod, we don't have a sure way to know if the debug configs are being applied
We want a sure way to know the finalized alpha router configs, now that both routing-api and [smart-order-router](https://github.com/Uniswap/smart-order-router) synthesize the alpha router configs quite a bit.
We only want to log finalized alpha router configs, when the upstream sends debugRoutingConfig.debugRouting = true. Otherwise we have too many logs.
=> add sor conditional logging on debug routing config override

src/routers/alpha-router/functions/get-candidate-pools.ts
Bug Fix
We are currently looking for 2 Token/Eth pools, but there can ever only be 1.
look only for 1 pool
=> There can ever only be 1 Token/Eth pool

src/providers/caching-token-list-provider.ts
- feature
- `CachingTokenListProvider.getTokens` only able to fetch specific tokens by addresses
- if no address array is passed in to `getTokens` it will return a `TokenAccessor` containing **_all_** of the chain's tokens from the token list
- This allows visibility into all of the chain's token from the token list which can be iterated over.
=> Get All Tokens From List

src/routers/alpha-router/alpha-router.ts, src/routers/router.ts
Telemetry
We don't have a top-level request latencies breakdown between cached routes vs non-cached routes.
We want this visibility. The only way to know is that [smart-order-router](https://github.com/Uniswap/smart-order-router) starts returning that boolean flag.
The boolean needs to be optional, so that the response schema is backward compatible. It's a debug only flag anyway.
=> add hits cached routes boolean flag

src/providers/provider.ts, src/routers/alpha-router/alpha-router.ts, src/routers/alpha-router/gas-models/gas-model.ts, src/routers/alpha-router/gas-models/mixedRoute/mixed-route-heuristic-gas-model.ts, src/routers/alpha-router/gas-models/v2/v2-heuristic-gas-model.ts, src/routers/alpha-router/gas-models/v3/gas-costs.ts, src/routers/alpha-router/gas-models/v3/v3-heuristic-gas-model.ts, src/routers/alpha-router/quoters/v2-quoter.ts, src/util/gas-factory-helpers.ts, src/util/routes.ts, test/test-util/mock-data.ts, test/unit/providers/caching/route/test-util/mocked-dependencies.ts, test/unit/routers/alpha-router/gas-models/mixed-route-gas-model.test.ts, test/unit/routers/alpha-router/gas-models/test-util/mocked-dependencies.ts, test/unit/routers/alpha-router/gas-models/v2-gas-model.test.ts, test/unit/routers/alpha-router/gas-models/v3-gas-model.test.ts
Adds an optional parameter `additionalGasOverhead` to ProviderConfig parameter of `buildGasModel` which applies a specified overhead to the gas estimate.
We were not previously accounting for the additional gas cost in trading ETH on V2/V3 pools as it must be wrapped/unwrapped into WETH every swap. This is very important for UniswapX as this is making it harder for X orders to beat out classic if our gas estimate is incorrect.
I also went ahead and added some very basic unit tests to the gas models.
I think my local prettier setup might be wrong, causing the large diff... I ran the prettier command but that changed like 30 files lol so maybe another PR.
TODO: 
- implement for V2 routes, that factory is …
=> Add weth wrap / unwrap gas cost to heuristics and add unit tests for gas models

src/providers/caching/route/model/cached-route.ts, test/unit/providers/caching/route/model/cached-route.test.ts
feature
no routeId exists for cached route
this creates a route id param
=> Create a routeId in CachedRoute

src/routers/alpha-router/functions/compute-all-routes.ts, test/test-util/mock-data.ts, test/unit/routers/alpha-router/alpha-router.test.ts, test/unit/routers/alpha-router/functions/compute-all-routes.test.ts
BugFix/Feature
Currently we will compute routes that represent arbitrage opportunities, when we go back to a previously seen token in the same route, this is a problem because we don't operate at the MEV level, so offering these routes to our users is not ideal, nor a good idea.
In this new behavior we keep track of the tokens visited per route, and we avoid visiting it again.
=> Keep track of tokens visited and avoid visiting back a token

src/routers/alpha-router/alpha-router.ts, src/routers/alpha-router/quoters/base-quoter.ts, src/routers/alpha-router/quoters/mixed-quoter.ts, src/routers/alpha-router/quoters/v2-quoter.ts, src/routers/alpha-router/quoters/v3-quoter.ts
small optimization
currently we quote all the distribution percents even if there's only 1 route
we will only quote the 100% amount when we have only 1 route
=> Only quote the 100% amount when there's only 1 route

src/routers/alpha-router/alpha-router.ts
Feature/Test
Right now cachemode could be livemode or tapcompare when we geth a cachedroute, but in practice it is always livemode
When we receive an expired cachedroute we should switch to tapcompare, this is a test we are doing to collect metrics
=> When CachedRoutes are expired, set cacheMode to Tapcompare manually

src/routers/alpha-router/alpha-router.ts
Feature
no config allow us to overwrite the cachemode
now we can pass a config that forces the cachemode
~
=> Create config to overwrite cachemode

src/providers/tenderly-simulation-provider.ts
Tenderly has new support for quick and accurate gas estimations (https://blog.tenderly.co/how-tenderly-enables-most-accurate-ethereum-gas-estimation/), we can enable this by passing `simulation_type` as `quick` in the simulation bodies.
=> feat: use tenderly quick simulation

src/providers/v2/quote-provider.ts, src/routers/alpha-router/alpha-router.ts, src/routers/alpha-router/quoters/v2-quoter.ts, test/test-util/mock-data.ts, test/unit/providers/v2/quote-provider.test.ts
Big fix
There's a bug in the FOT quote and routes calculation path, so that it would cause interface to double quote FOT tax immediately, if we ship https://github.com/Uniswap/routing-api/pull/362 today.
Let's use BULLET => WETH as an example. Hypothetically interface will issue two requests:
1. BULLET => WETH exact in with enableFeeOnTransferFeeFetching = true. Then it will writes the routes DB with the cached routes with the pool reserves with the buyFeeBps and sellFeeBps . Interface issued this request as part of their QA/testing.
2. Degen uses interface issue a BULLET => WETH exact in quote. Since interface has not enabled …
=> Fix: quote provider has the enable fot flag awareness

src/providers/provider.ts, src/providers/tenderly-simulation-provider.ts, src/routers/alpha-router/alpha-router.ts, test/integ/routers/alpha-router/alpha-router.integration.test.ts
Feature
If the integ-test failes because of tenderly simulation failure, we don't have an audit trail of tenderly simulation call stack.
Expose tenderly saveIfFailed flag and pass down to the tenderly request object.
=> Feature: expose tenderly saveIfFail flag through alpha-router

src/providers/token-fee-fetcher.ts, src/providers/token-properties-provider.ts, src/providers/token-validator-provider.ts
Observability
We see sporadic FOT quote without FOT tax. We have a theory, but we need to improve logging and metrics to be sure.
Add more logging and metrics.
Those new metrics together will tell us that when the FOT tax is not returned for FOT token, it will tell us:
1. if it's due to the token-validator contract call failure, then `TokenValidatorProviderValidateFailed` will increment and shows up in the log insights within the same request id. Also the logs containining 'Failed to validate token' will definitively show up now, vs at 10% chance previously.
2. if …
=> logging more around fot tax

cli/base-command.ts, src/providers/cache-node.ts, src/providers/cache.ts, src/providers/token-properties-provider.ts, src/routers/alpha-router/alpha-router.ts, test/integ/routers/alpha-router/alpha-router.integration.test.ts, test/unit/providers/cache-node.test.ts, test/unit/providers/token-properties-provider.test.ts
Bug fix
Token validator providers can return out-of-order results for the input token addresses. Coupled with the long caching TTL across all token properties entries, it can provider very negative experiences to the clients.
Token properties provider remove the calls to token validator providers. Also enhanced the `NodeJSCache` to accept per-entry TTL, so that token properties provider can set differentiated per-entry TTL depending on if it's positive cache or negative cache.
tested on the routing-api integ-test side via personal AWS …
=> Fix: Remove token validator provider calls from token properties provider

src/providers/token-fee-fetcher.ts, src/providers/token-properties-provider.ts, test/test-util/mock-data.ts, test/unit/providers/token-fee-fetcher.test.ts
Bug fix.
After shipping https://github.com/Uniswap/smart-order-router/pull/408, we start to see `TokenFeeFetcherFetchFeesFailure` metric showing up in prod. After investigation, this is due to [FeeOnTransferDetector](https://etherscan.io/address/0x19C97dc2a25845C7f9d1d519c8C2d4809c58b43f#code) reverted with `SameToken` error. This is possible when either tokenIn or tokenOut is ETH/WETH.
From sor runtime, we don't pass in the address that's corresponding to the `BASE_TOKEN`.
Formatted both TokenPropertiesProvider and TokenFeeProvider files. …
=> Fix: base token no fot fee lookup

src/providers/token-fee-fetcher.ts, test/unit/providers/token-properties-provider.test.ts
Bug fix
I noticed that after shipping https://github.com/Uniswap/smart-order-router/pull/410, somehow there were still `SameToken` error. I was test trying some ETH => BITBOY quote last night in prod, and noticed that some quote still doesn't have FOT tax. For example this [quote](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#logsV2:logs-insights$3FqueryDetail$3D~(end~0~start~-3600~timeType~'RELATIVE~unit~'seconds~editorString~'fields*20*40timestamp*2c*20*40message*2c*20*40logStream*2c*20*40log*0a*7c*20filter*20*40message*20like*20*27ccd67598-fe11-40a8-9dad-b71e16261dd9*27*0a*7c*20sort*20*40timestamp …
=> fix base token lower casing for comparison

src/providers/v2/caching-pool-provider.ts
Bug fix
There might be a race condition, where a quote request without `enableFeeOnTransferFeeFetching` flag can result in v2 caching-pool-provider to cache the pool entity without the FOT tax. Then within the same block, anothg quote request with `enableFeeOnTransferFeeFetching` flag can hit V2DynamoPair cache, that returns the cached pool entity without the FOT tax, disregard the `enableFeeOnTransferFeeFetching` flag from second quote request. I wouldn't call it a bug, but we probably have to work around to unblock mobile. Due to enableFeeOnTransferFeeFetching feature flag, there might be prod quote traffic, that hits the …
=> Fix: in caching pool provider, always retrieve fot tax along with pool reserves in v2, and cache fot pool entity

src/providers/tenderly-simulation-provider.ts
Chore
We don't know tenderly latencies. We've been told we don't pass in quick, so we need to log request bodies. We also don't have a configurable request timeout to tenderly.
Address all above
=> Chore: log tenderly request body, log tenderly simulation latencies, as well as expose optional timeout for routing-api

package-lock.json, package.json, test/integ/routers/alpha-router/alpha-router.integration.test.ts, test/test-util/whales.ts, test/unit/providers/v2/quote-provider.test.ts
Release https://github.com/Uniswap/v2-sdk/pull/149
- What is the current behavior? (You can also link to an open issue here)
Prior to ship https://github.com/Uniswap/smart-order-router/pull/421, web FOT quote has double FOT taxation issue, hence https://github.com/Uniswap/smart-order-router/pull/421 was needed.
- What is the new behavior (if this is a feature change)?
After shipping https://github.com/Uniswap/smart-order-router/pull/421, web FOT quote no longer has double FOT taxation issue. However if the token in is FOT, then the exact-in quote will be larger than the actual swap, and such swap failure rate will increase. For example, BLASTER => WETH swap success rate drops after shipping …
=> Chore: bump v2-sdk to 3.2.3 in sor

src/routers/alpha-router/alpha-router.ts, src/routers/alpha-router/config.ts, src/routers/alpha-router/functions/get-candidate-pools.ts
Feature/BugFix
Currently AMPL, being a rebasing token, is paired with other tokens (namely COMP) in a way that the pools are broken. The AMPL/COMP pool is not synced, so the quoter believes theres more liquidity than there really is.
There's not an easy solution to this problem, so the approach we are taking is of ignoring all AMPL paired pools on second hops.
This feature actually supports adding more tokens to this list as needed. 
=> Avoid routing through AMPL on second hop

src/providers/tenderly-simulation-provider.ts
Bug fix
Currently we don't have monitoring against the downstream tenderly http call success rate
We are logging the http status from tenderly against the tenderly request count.
This was a follow-up item from the [incident](https://www.notion.so/uniswaplabs/New-tokens-swap-outages-on-Wallet-due-to-Tenderly-enforcing-HTTPS-aad4719087f0407d8a9b21f0137fd070?pvs=4#86b9072133b949a6b9e636dfcca1e76e). We cannot alert against tenderly simulation failures, because those could be genuine failures due to user wallet, market conditions, etc. However …
=> Fix: improve tenderly connection

cli/base-command.ts
Bug fix
SOR CLI still uses the deprecated Tenderly HTTP endpoint. It's going to be inaccessible.
Fix it to use HTTPS
Replicated https://github.com/Uniswap/smart-order-router/pull/426
=> Fix: cli tenderly base url

src/providers/v3/caching-pool-provider.ts
Bug fix
quoteGasAdjusted is different even though the quote request hits against the same pair with the same trading size at the same block:
1. https://app.warp.dev/block/k5WS8jCQ3eKG8OZA31pdzx
2. https://app.warp.dev/block/9EdaLB6WOA3xJzKcoXWvch
This is only reproable against prod endpoint. Local endpoint works fine. I suspect this is due to the in-memory pool caching.
Make the v3 caching-pool-provider block aware.
This issue is not repro'able on local account, so this can only be shipped in prod to see the effect.
=> Fix: caching pool provider cache key to be block aware

src/providers/caching-gas-provider.ts, src/providers/eip-1559-gas-price-provider.ts, src/providers/eth-gas-station-info-gas-price-provider.ts, src/providers/gas-price-provider.ts, src/providers/legacy-gas-price-provider.ts, src/providers/on-chain-gas-price-provider.ts, src/providers/static-gas-price-provider.ts, src/providers/tenderly-simulation-provider.ts, src/routers/alpha-router/alpha-router.ts
Bug fix
We have some quote 5xx error, due to `eth_feeHistory failing on mainnet: request beyond head block: requested x_block_number, head y_block_number`. This is due to Infura node pool eventual consistency - not all the node in the same Infura node pool has the same block header.
We pass in 'latest' in case quote request does not pass in the block number. This is to replace the numerical latest block number we pass to infura during `eth_feeHistory` RPC calls.
=> fix: eth_feeHistory by passing 'latest' block number, meanwhile preserving the researcher's ability to quote against past number including gas fees

src/providers/v3/gas-data-provider.ts, src/routers/alpha-router/gas-models/v3/v3-heuristic-gas-model.ts, src/util/gas-factory-helpers.ts, test/unit/providers/v3/gas-data-provider.test.ts, test/unit/routers/alpha-router/util/gas-factory-helpers.test.ts
This PR fixes 2 bugs that causes inflated network cost (gas fee) estimate for Arbitrum.
Smart Order Router is inflating the Arbitrum fee due to double counting L1 fee and a incorrect unit conversion
1. Removed double counting of L1 fee in calculateGasUsed logic
2. Converted per byte fee into per gas fee by dividing 16 
See discussions in https://github.com/Uniswap/smart-order-router/pull/464 for original PR. This PR is created because it runs within [https://github.com/Uniswap/smart-order-router](https://github.com/Uniswap/smart-order-router) …
=> copy fix: arbitrum network cost estimate

test/integ/routers/alpha-router/alpha-router.integration.test.ts
Follow-up from https://github.com/Uniswap/smart-order-router/pull/468/files#diff-b1a09e5a7156f19225eba6ca4e2e78d0942580ff1118bab472bf0ea3b1294904R3581
=> chore: check gas estimate across L2s

src/routers/alpha-router/alpha-router.ts, src/util/chains.ts, test/integ/routers/alpha-router/alpha-router.integration.test.ts
Bug fix
Arbitrum subgraph is having problem for couple days.. Before we enable [V2_SUPPORTED](https://github.com/Uniswap/smart-order-router/pull/465/files#diff-f3f77a5e3d0a3c99c85eca60409b77f685b1ca0fe3e1a9e63cb45523905682afR28) in SOR, v3 subgraph issue would result in 404 no route. Now with v2 support, it will get all the pools metadata as part of [getHighestLiquidityUSDPool](https://github.com/Uniswap/smart-order-router/blob/main/src/routers/alpha-router/gas-models/v2/v2-heuristic-gas-model.ts#L220), so SOR/routing-api will now throw at [L254](https://github.com/Uniswap/smart-order-router/blob/main/src/routers/alpha-router/g …
=> fix: remove arb from v2 support

package-lock.json, package.json, test/integ/routers/alpha-router/alpha-router.integration.test.ts
Test improvements.
Integ-tests don't retry, and they often fail flakily.
Install jest-circus to enable integ-tests retry.
=> chore: jest-circus to enable integ-tests retry

package-lock.json, package.json, src/routers/alpha-router/alpha-router.ts
Bug fix and chore
V2_Supported array is being used in the gas model calculation, so that routing-api override doesn't work.
makes it a alpha router config.
release to v3.24.4 as well
=> fix & chore: fix v2 supported bug & bump to v3.24.4

src/routers/alpha-router/alpha-router.ts, src/util/chains.ts
Bug fix
V2 swap is not supported on Sepolia
We already deployed V2 universal router and factory to Sepolia, we can support Sepolia on L2.
=> add sepolia to v2 supported array

src/providers/v3/gas-data-provider.ts
Bug fix
OP gas oracles disabled [overhead](https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/src/L2/GasPriceOracle.sol#L70) and [scalar](https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/src/L2/GasPriceOracle.sol#L78) after Dencun/Ecotone
Hardcode overhead and scalar to make swap work on OP and OP-stack networks
Proper fix requires adopting OP gas estimate SDK
=> fix: op gas oracles

package-lock.json, package.json, src/providers/eth-estimate-gas-provider.ts, src/providers/simulation-provider.ts, src/providers/tenderly-simulation-provider.ts, src/providers/v3/gas-data-provider.ts, src/routers/alpha-router/alpha-router.ts, src/routers/alpha-router/gas-models/gas-model.ts, src/routers/alpha-router/gas-models/v2/v2-heuristic-gas-model.ts, src/routers/alpha-router/gas-models/v3/v3-heuristic-gas-model.ts, src/routers/alpha-router/quoters/v2-quoter.ts, src/util/gas-factory-helpers.ts, src/util/l2FeeChains.ts, test/unit/routers/alpha-router/gas-models/v2-gas-model.test.ts, test/unit/routers/alpha-router/gas-models/v3-gas-model.test.ts, test/unit/routers/alpha-router/util/gas-factory-helpers.test.ts
feature
We don't use OP SDK to calculate L1 calldata posting gas
CLI quote working https://app.warp.dev/block/nauVxxYzFqribB6Q05tK9t
=> feat: adopt op sdk for L1 calldata posting gas

.github/workflows/tests.yml, package-lock.json, package.json, src/util/chains.ts
Release https://github.com/Uniswap/smart-order-router/pull/515
Also removes goerli from supported chains.
=> chore: bump to v3.26.0 and remove goerli from supported chains

package-lock.json, package.json
Release https://github.com/Uniswap/universal-router-sdk/pull/169
=> chore: bump ur-sdk to v1.8.2, support blast

src/providers/on-chain-quote-provider.ts
Bug fix
I noticed that the quote latencies between current quoter and view-only quoter do not look expected. Somehow exact out current quoter always has lower latencies than view-only quoter:
This is not expected, given that the view-only quoter consumes a lot less guess, and it does not simulate the swap:
I think the bug is in the routing-api latencies [logging](https://github.com/Uniswap/routing-api/blob/main/lib/handlers/quote/provider-migration/v3/traffic-switch-on-chain-quote-provider.ts#L67-L87) - meanwhile we use `Promise.all` to parallelize two quoters call, and use `then` to log the latencies, but since JS runtime …
=> fix: add quote latency metrics within onchain quote provider

src/providers/multicall-provider.ts, src/providers/multicall-uniswap-provider.ts, src/providers/on-chain-quote-provider.ts
feature
Meanwhile we are comparing the current quoter quotes vs new view-only quoter quotes in prod in shadow sampling for mainnet at 1%, we encounter a case, where we have some quotes that are failing due to the out-of-gas from multicall (e.g. this [simulation](https://www.tdly.co/shared/simulation/39de04bb-d794-43b0-aed2-8ea31957ca77)), but from routing-api side, we don't have a good way to programmatically determine this is the case, within [compareQuotes](https://github.com/Uniswap/routing-api/blob/d05f590db3facdc76850fb3ade374b17f485d315/lib/handlers/quote/provider-migration/v3/traffic-switch-on-chain-quote-provider.ts#L21 …
=> fix: multicall return gas used in case of failure

src/util/addresses.ts
chore
Since we are using the same deployer wallet to deploy, most likely the first deployed address will be the same across chains. We are enumerating the view-only quoter address for now.
We don't enumerate the view-only quoter address per chain, unless that particular chain has a different deploy address. This will speed up our new chain deploy, where we can just ship changes in routing-api for each newly deployed quoter on a new chain.
=> chore: use single default view-only quoter deploy address

src/util/addresses.ts
feature
Base has a distinct view-only quoter address
Adding the distinct view-only quoter address on Base
See https://basescan.org/address/0xf0c802dcb0cf1c4f7b953756b49d940eed190221#code for deployed contract
=> add new view quoter address on base

src/util/addresses.ts
Big fix
Since shadow quoting in Base today (https://github.com/Uniswap/routing-api/pull/598), the accuracy has been low:
I used tenderly [simulation](https://www.tdly.co/shared/simulation/cf37f5ed-5eaf-49f6-b966-fc33c10e0748) to debug, then I noticed the computed pool address from the view-only quoter is non-existent on Base. I was using the wrong v3 core factory when deploying to Base. I already fixed that and re-deployed https://github.com/Uniswap/view-quoter-v3/pull/12, but we also need to update the quoter deploy address in SOR, so that routing-api quote accuracy can go up on Base.
- **What is the new behavior (if this is …
=> fix: update view-only quoter address in base

src/providers/v2/subgraph-provider.ts, src/providers/v3/subgraph-provider.ts
Create a way for the SubgraphProviders to receive an override URL.
This will be used in RoutingAPI to pull the url from a secret for our custom subgraphs
=> Allow SubgraphProviders to receive a URL override

src/providers/on-chain-quote-provider.ts
Bug fix
When in mixed quote path, we fallback to the revert quoter
When in mixed quote path, we should fallback to the view-only quoter now.
I expect the overall quote endpoint latency to improve along with the gas param tuning.
=> fix: mixed quoter fallback to new view-only quoter

src/providers/on-chain-quote-provider.ts
chore
We don't log quote success rate metrics. In case of low success rate, quote has to retry and impacts the latencies.
We are tracking the per-chain v3/mixed quoter success rate, this includes the initial success rate as well as the retried success rate.
=> chore: log quote sucecss rate metric

src/providers/v2/subgraph-provider.ts, src/providers/v3/subgraph-provider.ts
The V2 and V3 Subgraph Providers are currently returning pools that contain more fields than are necessary.
When we store these fields in our S3 bucket in routing-api we end up with additional data that increase our blob size, and we don't need them.
This PR removes the additional fields
=> chore(subgraph): Remove not necessary fields

src/providers/on-chain-quote-provider.ts, src/providers/provider.ts, src/routers/alpha-router/quoters/mixed-quoter.ts, src/routers/alpha-router/quoters/v3-quoter.ts
chore
We don't differentiate the metrics between quote-intent quote vs caching-intent quote inside on-chain quoter 
We need to make this distinction. I noticed the caching-intent quote endpoint latency is improving with the gas param tuning, but not quote-intent quote. This is possible, because quote-intent quote runs through less routes than caching-intent quote. I need to make gas tuning against quote-intent quote only.
=> chore: log optimistic quote metrics prefix in onchain quoting

src/providers/on-chain-quote-provider.ts, src/routers/alpha-router/alpha-router.ts
chore
We don't differ gas batch param by intent-quote vs caching-quote.
We will differentiate
=> chore: onchain quoter batch param differed by optimistic cached routes

src/providers/on-chain-quote-provider.ts
feature
Current gas param doesn't differ by protocol version
Now gas param will differ by protocol version. This is important, because mixed-quoter-v1 is gas-inefficient in terms of reverting to get quote for V3 pools of the mixed path.
=> feat: gas param also by protocol version

src/providers/v2/subgraph-provider.ts, src/providers/v3/subgraph-provider.ts
Add metrics to measure untracked pools thresholds, this change is a no-op for the live feature but it will allow us to measure the impact of allowing untracked pools in the cache.
=> chore(subgraph): Add metrics to measure untracked pools thresholds

src/util/chains.ts
Bug fix
I saw routing-api pipeline failed with blast tests. Digging into it, it's because blast weth address is wrong to compute v3 gas model.
Fix blast weth address.
This only impacts the route going through v3. For v2 route, since we don't compute the WETH/USDC gas model, the quote can still work.
=> fix: blast weth address

src/providers/token-properties-provider.ts, test/unit/providers/token-properties-provider.test.ts
Bug fix
We don't get fee fetch [cache hits](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#metricsV2?graph=~(metrics~(~(~'Uniswap~'TokenFeeFetcherFetchFeesFailure~'Service~'RoutingAPI)~(~'.~'TokenFeeFetcherFetchFeesSuccess~'.~'.)~(~'.~'TokenPropertiesProviderBatchGetCacheMiss~'.~'.))~sparkline~true~view~'timeSeries~stacked~false~region~'us-east-2~start~'-PT24H~end~'P0D~stat~'SampleCount~period~60)&query=~'*7bUniswap*2cService*7d*20TokenPropertiesProviderBatchGetCacheHit) due to misconfigured batchGet keys.
With this fix we should start seeing cache hits and a big qps reduction. Also updated/fixed …
=> Fix cache batchGet keys + update unit test

.github/workflows/tests.yml, test/integ/routers/alpha-router/alpha-router.integration.test.ts
Bug fix
We forked a block, where WETH/USDC v3 pool was not as deep liquid, so some simulated swap tests failed, as well as the slippage was over 15% at that block.
We will fork at a block close to the current finalized block, and see if the failed integ-tests can be fixed as much as possible.
=> fix: failing integ-tests

src/providers/simulation-provider.ts, src/providers/tenderly-simulation-provider.ts, test/integ/routers/alpha-router/alpha-router.integration.test.ts
Bug fix
We are using wrong permit2 address on ZkSync.
We will use correct permit2 address by importing from permit2-sdk
No
=> fix: use permit2-sdk PERTMIT2_ADDRESS

src/providers/token-properties-provider.ts
Increase token fee data cache ttl to 20m.
FOT fees don't change often so we are ok increasing this caching time, should be enough to reduce onchain requests due to lambda recycling
10m caching
20m caching
=> chore(caching): Increase token fee data cache ttl to 20m

package-lock.json, package.json
To pickup fee token fetch caching ttl increase change ([PR](https://github.com/Uniswap/smart-order-router/pull/606))
=> chore: bump sor to 3.35.3

src/providers/tenderly-simulation-provider.ts
Bug fix
Because in routing-api, we set logging at info level at 10% percent chance upon lambda instantiation (https://github.com/Uniswap/routing-api/blob/main/lib/handlers/quote/injector.ts#L40), 90% of the chance log.info won't log anything. In order to troubleshoot tenderly gas mismatch, e.g. for this request id [19ec5e03-5abb-420d-979d-e765e7923eac](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#logsV2:logs-insights$3FqueryDetail$3D~(end~0~start~-3600~timeType~'RELATIVE~unit~'seconds~editorString~'fields*20*40timestamp*2c*20*40message*2c*20*40logStream*2c*20*40log*0a*7c*20filter*20*40message*20like …
=> fix: add tenderly simulation request bodies in the mismatch error logging

src/routers/alpha-router/gas-models/gas-model.ts
Bug fix
USDC has 6 decimals, DAI has 18 decimals.
```
// For each gas estimate, normalize decimals to that of the chosen usd token.
const estimatedGasUsedUSDs = _(bestSwap)
.map((routeWithValidQuote) => {
// TODO: will error if gasToken has decimals greater than usdToken
const decimalsDiff =
usdTokenDecimals - routeWithValidQuote.gasCostInUSD.currency.decimals;
if (decimalsDiff == 0) {
return CurrencyAmount.fromRawAmount(
usdToken,
routeWithValidQuote.gasCostInUSD.quotient
);
}
return CurrencyAmount.fromRawAmount(
usdToken,
JSBI.multiply(
routeWithValidQuote.gasCostInUSD.quotient,
JSBI.exponentiate(JSBI.BigInt(10), …
```
=> fix: use DAI as first gas token

src/providers/tenderly-simulation-provider.ts
Bug fix
We return simulation error on zksync, meanwhile tenderly doesn't support zksync simulation yet. So we should return tenderly not supported.
return tenderly not supported on zksync.
=> fix: return tenderly not supported on zksync

src/providers/tenderly-simulation-provider.ts
Bug fix
I think it's possible that the node gas estimate didn't return the gas/gasUsed for some requests:
Both request and nodeGas are undefined/NaN. This is possible in case the node gas estimate returns a failed response.
We should log the entire request body and response payload to account for this situation.
We log them correctly so that we can debug
We will log the entire request and response.
=> fix: tenderly node request param array indexing

src/providers/tenderly-simulation-provider.ts
Bug fix
In case of simulated onchain revert from tenderly, e.g.:
```
INFO:  Tenderly estimate gas bundle request body: {
"id": 1,
"jsonrpc": "2.0",
"method": "tenderly_estimateGasBundle",
"params": [
[
{
"from": "0x67c231cF2B0E9518aBa46bDea6b10E0D0C5fEd1B",
"to": "0x0F5D2fB29fb7d3CFeE444a200298f468908cC942",
"data": "0x095ea7b3000000000000000000000000000000000022d473030f116ddee9f6b43ac78ba3ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"
},
{
"from": "0x67c231cF2B0E9518aBa46bDea6b10E0D0C5fEd1B",
"to": "0x000000000022D473030F116dDEE9F6B43aC78BA3",
"data": …
```
=> fix: tenderly node error response

src/providers/tenderly-simulation-provider.ts
Bug fix
Besides small amount of tenderly API vs tenderly node response mismatch, I noticed small amount of [TenderlyNodeGasEstimateBundleFailure](https://github.com/Uniswap/smart-order-router/blob/5b86d2f707d875ed4ebe9639f73c5c9f2a752c6b/src/providers/tenderly-simulation-provider.ts#L868).
This is due to:
If I hit against the same tenderly node endpoint with the same payload, I got a result array:
```
{"id":1,"jsonrpc":"2.0","result":[{"error":{"code":3,"message":"execution reverted","data":"0x"}},{"gas":"0x77e6","gasUsed":"0x77e6"},{"gas":"0x29cee","gasUsed":"0x23bac"}]}%         
```
This tells me that `Cannot read …
=> fix: log error response in case of tenderly node non 200 http status

.github/workflows/npm-audit-fix.yml
Fixes the npm audit fix arguments
=> fixes the arguments for the npm audit fix action

src/providers/tenderly-simulation-provider.ts
Bug fix
tenderly API simulation does not include block number on permit2 and UR approvals
tenderly API simulation to include block number on permit2 and UR approvals
=> fix: tenderly API simulation missing block number on permit2 and UR approvals

src/providers/tenderly-simulation-provider.ts
Bug fix
From tenderly:
> Yes, on the API, if you specify bn 100, we take the state of bn 99 and create a new block 100 where we simulate at the beginning.
On the Node, if you specify bn 100, we take the state of block 100, and create a fake block 101 where we simulate.
Make (blocknumber - 1) for tenderly node simulation. From tenderly:
> So I'd recommend adding the following changes to check if the diffs remain:
> - add the block_number parameter to all sims in the API bundle
> - use block_number - 1 for the Node bundle
=> fix: tenderly node simulation block with (block number - 1)

src/providers/tenderly-simulation-provider.ts
Bug fix
Turned out we should not subtract block number from 1 for node request
Revert previous change.
=> Revert "fix: tenderly node simulation block with (block number - 1) (#629)"

src/providers/v2/subgraph-provider.ts, src/providers/v3/subgraph-provider.ts
In order to triage the issue of high latency when loading the subgraph, we need to know the page in which it fails.
This change will hopefully provide this information.
=> chore(subgraph): Add error logs for subgraph pool fetching

src/providers/simulation-provider.ts, src/providers/tenderly-simulation-provider.ts, test/unit/providers/simulation-provider.test.ts
Remove unncessary mainnet check when trying ethEstimateGas
- Currently we go straight to tenderly for all natives except for mainnet, when we shouldnt. 
We will try ethEstimategas for all native tokens of all chains, and fallback to tenderly if it fails.
=> Remove unncessary mainnet check when trying ethEstimateGas

src/providers/on-chain-gas-price-provider.ts, src/util/l2FeeChains.ts
Bug fix
SOR return legacy gas price for OP stack chains and arbitrum
SOR return EIP-1559 gas price for OP stack chains and arbitrum
=> fix: eip-1559 gas model for arbitrum and op stack chains

src/providers/tenderly-simulation-provider.ts
Bug fix
There are some unexpected error from shadow calling tenderly node endpoint:
```
TypeError: Cannot read properties of undefined (reading 'length')
at vCe.sampleNodeEndpoint (/node_modules/@uniswap/smart-order-router/src/providers/tenderly-simulation-provider.ts:791:67)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
hostname	
169.254.94.253
level	
50
msg	
Failed to invoke Tenderly Node Endpoint for gas estimation bundle {
"id": 1,
"jsonrpc": "2.0",
"method": "tenderly_estimateGasBundle",
"params": [
[
{
"from": "0xc1092Fff8e8d0208167040143C10b8eDCAB17e63",
"to": …
```
=> fix: add node response logging for undefined error

.github/workflows/tests.yml, src/providers/tenderly-simulation-provider.ts, test/integ/routers/alpha-router/alpha-router.integration.test.ts
feature
We are only shadow sampling tenderly node endpoint. Now that tenderly fixed the final gas estimate bug, we consistently see 100% gas estimate matches:
We are implementing the tenderly node live switch feature.
In integ-test, we set the migration percent to 100%, so that all the simulation tests always use tenderly node endpoint for testing coverages.
=> feat: tenderly support live switch with integ-test coverage

.github/workflows/release.yml
Fixes the deploy script to have write ability inside github to make a github release
=> chore(infra): adds write permissions to the gh action

src/routers/alpha-router/alpha-router.ts, src/routers/alpha-router/functions/compute-all-routes.ts, src/routers/alpha-router/functions/get-candidate-pools.ts, src/routers/alpha-router/quoters/base-quoter.ts, src/routers/alpha-router/quoters/mixed-quoter.ts, src/routers/alpha-router/quoters/model/results/get-routes-result.ts, src/routers/alpha-router/quoters/v2-quoter.ts, src/routers/alpha-router/quoters/v3-quoter.ts, src/routers/alpha-router/quoters/v4-quoter.ts, src/routers/router.ts, test/unit/routers/alpha-router/functions/compute-all-routes.test.ts
feature
After getting the top v4 candidate pools by TVL, we need to compute the v4-only routes.
We are implementing computeV4Routes as part of v4-quoter, that will get invoked by alpha router.
It's protected under explicitly protocol version specification.
=> feat: implement v4-quoter with computeV4Routes and stub getQuotes (invoke onchain quoter provider class)

src/routers/alpha-router/alpha-router.ts, test/test-util/mock-data.ts, test/unit/routers/alpha-router/alpha-router.test.ts
Bug fix
We will attempt to quote a FOT pair against v3 quoter or mixed quoter.
FOT doesn't work in v3 pool. This means quoting against v3 quoter or mixed quoter (which goes through at least one v3 pool of the mixed route) doesn't work. If we see the tokenIn is sell FOT tax or tokenOut is buy FOT tax, then we only go through v2 quoter.
Testing wise, I'm relying on the existing e2e tests in both SOR and routing-api. On SOR level, it never goes through cached routes, so it will test against `swapRouteFromChain`. On routing-api level, we …
=> fix: for token pair only quote against v2 quoter

src/providers/subgraph-provider.ts, src/providers/token-provider.ts, src/providers/v3/subgraph-provider.ts, src/providers/v4/subgraph-provider.ts, src/routers/alpha-router/alpha-router.ts, src/routers/alpha-router/functions/best-swap-route.ts, src/routers/alpha-router/functions/get-candidate-pools.ts, src/routers/alpha-router/gas-models/gas-costs.ts, src/routers/alpha-router/gas-models/gas-model.ts, src/routers/alpha-router/gas-models/mixedRoute/mixed-route-heuristic-gas-model.ts, src/routers/alpha-router/gas-models/tick-based-heuristic-gas-model.ts, src/util/chains.ts, src/util/methodParameters.ts, test/integ/routers/alpha-router/alpha-router.integration.test.ts, test/unit/providers/on-chain-quote-provider.test.ts
feature
best swap route does not account for v4 routes
best swap route is now implemented to account for v4 routes.
I added v4 routing integ-test against alpha router, in [alpha-router.integration.test.ts](https://github.com/Uniswap/smart-order-router/pull/680/files#diff-b1a09e5a7156f19225eba6ca4e2e78d0942580ff1118bab472bf0ea3b1294904). I can see the alpha router can quote 1 OP -> 997404.407521 USDC against pool id 0xa40318dea5fabf21971f683f641b54d6d7d86f5b083cd6f0af9332c5c7a9ec06. Tenderly simulation does not work yet, because universal …
=> feat: implement best swap route with v4 routes

test/integ/routers/alpha-router/alpha-router.integration.test.ts, test/test-util/whales.ts
Bug fix
We have couple failing alpha router integ-tests failures.
For https://github.com/Uniswap/smart-order-router/actions/runs/10619450187/job/29437060538#logs, failed test is due to its forked on the block where the test swapper's permit2 nonce is greater than one, indicated by https://app.warp.dev/block/ErFSU72zpWZFxOzeRhEq5h. We just have to find the forked block that can reset that swapper's input token's permit2's nonce back to 1. Luckily changing forked block from 2041390 to 20444945 will do.
For all other integ-tests failures, it's due to not large enough …
=> fix: alpha router integ tests

src/routers/alpha-router/alpha-router.ts
- Fixes exception throwing in from logging code
throws exception when logging fails with div by zero
logs metric but doesn't throw
=> fix(sor): catch div zero + log but don't throw

src/routers/alpha-router/gas-models/tick-based-heuristic-gas-model.ts
Fixes division by zero exception when `gasCostInTermsOfAmountToken` is zero
```
{"name":"quote","requestId":"a54ba5b5-5a11-4cda-8c63-3775099f5bad","hostname":"169.254.29.161","pid":12,"quoteId":"a54ba","tokenInAddress":"0x48065fbBE25f71C9282ddf5e1cD6D6A887483D5e","chainId":42220,"tokenOutAddress":"0xcebA9300f2b948710d2653dD7B07f33A8B32118C","amount":"10","type":"exactIn","activityId":"ead33689-86ae-4a04-b4fc-40b43a985a04","level":50,"err":{
"message":"Division by zero",
"name":"RangeError",
"stack":"RangeError: Division by zero\n    
at Function.divide (/node_modules/jsbi/lib/jsbi.ts:228:31)\n    
at e.get (/node_modules/@uniswap/sdk-core/src/entities/fractions/fraction.ts:43:17)\n    
at e …
```
=> fix: div by zero on syntheticGasCostInTermsOfQuoteToken

src/routers/alpha-router/alpha-router.ts, src/routers/alpha-router/functions/best-swap-route.ts, src/routers/alpha-router/quoters/mixed-quoter.ts, src/util/methodParameters.ts, src/util/routes.ts, test/integ/routers/alpha-router/alpha-router.integration.test.ts, test/unit/providers/token-fee-fetcher.test.ts, test/unit/routers/alpha-router/functions/routes.test.ts
feature
For mixed protocol version request, we don't have the ability to exclude a certain route with a certain pool version. Some clients would love to still request mixed routes, but they don't want any of the mixed route to go through any v4 pools.
We will expose a new additional generic field `excludedProtocolsFromMixed` to be able to exclude certain protocol version pool routes from the mixed routes.
We can be somewhat limited in scope in the protocol exclusions here. If someone says I don't want pure v3-pool routes returned from SOR, …
=> feat: exclude certain protocol versions from mixed routing

package-lock.json, package.json, src/providers/provider.ts, src/providers/tenderly-simulation-provider.ts, src/routers/alpha-router/alpha-router.ts, src/routers/alpha-router/gas-models/tick-based-heuristic-gas-model.ts, src/routers/router.ts, src/util/gas-factory-helpers.ts, src/util/methodParameters.ts, src/util/routes.ts, test/integ/routers/alpha-router/alpha-router.integration.test.ts, test/test-util/whales.ts, test/unit/providers/portion-provider.test.ts, test/unit/providers/simulation-provider.test.ts, test/unit/routers/alpha-router/alpha-router.test.ts
feature
With V4, protocol team will deploy a new version (v2.0) of universal router. Currently, in ur-sdk, we introduced UniversalRouterVersionEnum as part of UniversalRouterAddress function param. However, SOR needs to bump up ur-sdk to adopt UniversalRouterVersionEnum.
SOR to support passing in universal router version param as part of alpha router config
=> feat: SOR support universal router version param as part of alpha router config

package-lock.json, package.json, src/routers/alpha-router/functions/compute-all-routes.ts, src/routers/alpha-router/gas-models/mixedRoute/mixed-route-heuristic-gas-model.ts, src/routers/alpha-router/quoters/base-quoter.ts, src/util/routes.ts, test/unit/routers/alpha-router/gas-models/mixed-route-gas-model.test.ts
Chore
We don't use TPool from router-sdk. As a result, we have repeated TPool type across SOR code.
We use TPool from router-sdk
=> chore: bump router-sdk to 1.11.2 and use TPool from router-sdk

src/providers/token-properties-provider.ts, src/providers/v2/pool-provider.ts, src/routers/alpha-router/alpha-router.ts, src/util/addresses.ts
feature 
token properties provider accepts token. In case of native currencies for v4 pools, we'd like to be able to accept native currency type.
We modify token properties provider to accept currencies.
=> feat: convert token properties provider to accept currency instead of token

src/providers/caching/route/model/cached-routes.ts, src/providers/caching/route/route-caching-provider.ts, src/providers/token-properties-provider.ts, src/routers/alpha-router/alpha-router.ts, src/util/addresses.ts, test/unit/providers/caching/route/model/cached-routes.test.ts, test/unit/providers/caching/route/test-util/inmemory-route-caching-provider.ts, test/unit/providers/caching/route/test-util/mocked-dependencies.ts, test/unit/routers/alpha-router/functions/routes.test.ts
feature
cached routes do not support native currency routing
we want cached routes to support native currency routing. This is import for v4 native currency routing support.
Although we changed the method signature to accept Currency, for now we still pass in Tokens for tokenIn and tokenOut, so that this change should still remain no-op for now.
=> feat: cached routes to support native currencies

package-lock.json, package.json, src/providers/v3/static-subgraph-provider.ts, src/routers/alpha-router/functions/get-candidate-pools.ts, src/util/amounts.ts, src/util/gas-factory-helpers.ts, test/test-util/mock-data.ts, test/unit/routers/alpha-router/functions/get-candidate-pools.test.ts, test/unit/util/amount.test.ts
Upgrades to latest v3-sdk
Adding support for additional fee tiers
Those tiers will be supported for all chains if returned in subgraph, but they will be added by default only for Base.
Supporting 4 fee tiers
Supporting 3 additional fee tiers
See related [v3-sdk PR](https://github.com/Uniswap/sdks/pull/99)
=> feat: upgrade v3-sdk version + support additional fee tiers

package-lock.json, package.json
Bumps sor version to include https://github.com/Uniswap/smart-order-router/pull/704
4 fee tiers supported
3 additional fee tiers introduced
=> chore(sor): bump version to 3.55 - base additional fee tiers

src/abis/v4-periphery/V4Quoter.sol/V4Quoter.json, src/providers/on-chain-quote-provider.ts, src/routers/alpha-router/functions/best-swap-route.ts, src/util/addresses.ts, test/unit/providers/on-chain-quote-provider.test.ts
chore
We were pointing to the older version of v4 quoter, with obsolete ABI.
We are pointing to refactored v4 quoter, with concise ABI, from https://github.com/Uniswap/v4-periphery/pull/349.
I deployed quoter from that PR to https://sepolia.etherscan.io/address/0x9336CF25dDad216FD480A5422CBEa7b3BC5bDda8#code, so it's likely it's not the final quoter contract, until we finish auditing. However it's worth the effort to integrate with SOR, because ABIs are unlikely to change.
=> chore: update v4 quoter address and ABI

src/providers/caching/route/model/cached-route.ts, src/providers/on-chain-quote-provider.ts, src/providers/v4/pool-provider.ts, src/providers/v4/static-subgraph-provider.ts, src/routers/alpha-router/alpha-router.ts, src/routers/alpha-router/entities/route-with-valid-quote.ts, src/routers/alpha-router/functions/best-swap-route.ts, src/routers/alpha-router/functions/compute-all-routes.ts, src/routers/alpha-router/gas-models/v4/v4-heuristic-gas-model.ts, src/routers/alpha-router/quoters/base-quoter.ts, src/routers/alpha-router/quoters/mixed-quoter.ts, src/routers/alpha-router/quoters/v4-quoter.ts, src/util/gas-factory-helpers.ts, test/unit/providers/caching/route/test-util/mocked-dependencies.ts, test/unit/routers/alpha-router/alpha-router.test.ts, test/unit/routers/alpha-router/gas-models/mixed-route-gas-model.test.ts, test/unit/routers/alpha-router/gas-models/test-util/mocked-dependencies.ts, test/unit/routers/alpha-router/util/gas-factory-helpers.test.ts
Revert https://github.com/Uniswap/smart-order-router/pull/715
mixed routes part of the PR caused regression, when quote token is native currency, when it was trying to quote against gas token https://github.com/Uniswap/smart-order-router/pull/715/files#diff-fe1277629ea700a6f1ec3b7e45e13fa05da63f1372b433736a9c9d2284c75ad0R461. In prod it throws `Invariant failed: CURRENCY`
we revert https://github.com/Uniswap/smart-order-router/pull/715. Then we will break down the PR into finer PRs. we already know that only mixed routing part has issue, so we will break apart mixed …
=> Revert "feat(breaking): top-level alpha router native currencyIn, currencyIn, quoteCurrency support (#715)"

src/providers/caching/route/model/cached-route.ts, src/providers/on-chain-quote-provider.ts, src/providers/v4/pool-provider.ts, src/providers/v4/static-subgraph-provider.ts, src/routers/alpha-router/functions/compute-all-routes.ts, test/unit/routers/alpha-router/alpha-router.test.ts
feature
there are several code places where we simply wrap the currency, and thus not able to support native currency routing in v4.
we are removing the .wrapped implementations. We keep the alpha router to pass in the wrapped tokens into the quoters in this PR, for backward compatibility.
re-do https://github.com/Uniswap/smart-order-router/pull/715 with breakdowns
=> feat: part 1 native currency routing support by removing .wrapped in implementation classes

src/providers/token-provider.ts, src/routers/alpha-router/functions/get-candidate-pools.ts, test/integ/routers/alpha-router/alpha-router.integration.test.ts
Bug fix
Native currency routing has a bug of not properly considering the native currency candidate pools in v4
We will consider native currency pools in candidate pool. Native currency is not ERC20 token, so we cannot get metadata for the native currency. Therefore we should not filter out native currency
Added ETH -> USDC quote for v4 in sepolia.
=> fix: v4 subgraph not properly including native currency in v4 candidate pools

src/routers/alpha-router/alpha-router.ts, src/routers/alpha-router/quoters/base-quoter.ts, src/routers/alpha-router/quoters/v4-quoter.ts, src/util/gas-factory-helpers.ts
Bug fix
native currency routing quote is token not currency. v4 native currency quote cannot work. For example, ETH -> USDC exact out quote will not route through v4 ETH/USDC pool.
fix the quote token to be quote currency in the input path until on-chain quoter
for v4-quoter.ts output quote can be token. we will have to fix the v4 gas model to take quote token as currency type. more details in ROUTE-306
=> fix: native currency routing quote token has to be currency type

package-lock.json, package.json
Bug fix
ur-sdk wrong astrochain sepolia address
release https://github.com/Uniswap/sdks/pull/153
=> fix: bump sor to 4.5.2 - bump ur-sdk to 4.3.1

package-lock.json, package.json, src/providers/caching-subgraph-provider.ts, src/providers/v4/static-subgraph-provider.ts, src/routers/alpha-router/alpha-router.ts, src/routers/alpha-router/functions/get-candidate-pools.ts, src/util/amounts.ts, test/integ/routers/alpha-router/alpha-router.integration.test.ts
Bug fix
Right now v4 is hardcoded with v3 fee tiers and tickspacings. Also static subgraph provider is not able to get native ETH v4 pool.
allow routing-api to pass in more v4 custom fee tiers and tickspacings on a per-need basis. Also static subgraph should get ETH base token to get native v4 pool. Later is in case the v4 subgraph has too many bugs so that we cannot rely on live subgraph to filter by TVL.
=> chore: bump sor to 4.7.1 - fix: v4 subgraph provider add ETH base token, and custom fee tier and tick spacings

package-lock.json, package.json, src/routers/alpha-router/alpha-router.ts, src/util/routes.ts
Bug fix
forgot to emit v4 related split routes metrics
emit v4 related split routes metrics
this is to keep track of an edge case, that i dont expect happen frequently https://linear.app/uniswap/issue/ROUTE-303/tech-debt-split-route-can-have-different-ethweth-input-or-output#comment-a0b9a66a
=> chore: bump SOR to 4.7.2 - fix: add v4 related split routes metrics and routeToString

package-lock.json, package.json, src/routers/alpha-router/alpha-router.ts, src/util/index.ts, src/util/intent.ts, test/integ/routers/alpha-router/alpha-router.integration.test.ts, test/test-util/mock-data.ts, test/unit/providers/caching/route/test-util/inmemory-route-caching-provider.ts, test/unit/routers/alpha-router/gas-models/test-util/mocked-dependencies.ts
Bug fix
if the cached routes is invalid, meaning it cant get any swap route at all, it does not get cache invalidated.
we will invalidate the cached routes by checking to see if the swap route from cache is invalid
we have to roll out with percentage. because there's a chance there are many invalid cached routes in prod.
This is somewhat critical to fix prior to V4, because there's a chance that routing caches invalid v4-pool routes. Previously this wasn't much of a concern,. since V3 launched in 2021, and cached routes was rolled out in …
=> chore: bump sor to 4.7.5 - fix: cached routes cache invalidation

package-lock.json, package.json, src/routers/alpha-router/alpha-router.ts
Bug fix
We fire and forget the set cached routes
We await on set cached routes in both old and new code paths.
=> fix: await set cached routes

src/providers/simulation-provider.ts, src/providers/tenderly-simulation-provider.ts, test/unit/providers/simulation-provider.test.ts
Bug fix
Right now when tenderly has system downtime, we do not differentiate from when tenderly simulation returns a failed simulated transaction, in case of the Simulation Status, as FAILED.
In case of tenderly downtime, we return SystemDown simulation status from SOR.
It will get populated in routing to return a new simulation status as "SYSTEM_DOWN"
=> chore: bump to 4.7.8 - fix: return a new tenderly simulation status in case of tenderly downtime

package-lock.json, package.json, src/providers/tenderly-simulation-provider.ts, test/integ/routers/alpha-router/alpha-router.integration.test.ts
feature
we don't support new tenderly endpoint on base yet.
we will support new tenderly endpoint on base
=> chore: bump sor to 4.8.0 - feat: migrate base tenderly to new endpoint

src/providers/token-provider.ts, src/routers/alpha-router/functions/get-candidate-pools.ts, test/unit/routers/alpha-router/functions/get-candidate-pools.test.ts
Bug fix: 
We do filter out AMPL pools from subgraph query but direct swap pools are re-added by get-candidate-pools logic.
This PR prevents AMPL direct swap pools from getting re-added.
This is CX ask.
=> fix: Don't force add direct swap AMPL pools for V3 in candidate pools

package-lock.json, package.json
Bump SOR version for https://github.com/Uniswap/smart-order-router/pull/764
=> chore: bump sor to 4.8.1 - fix: Don't force add direct swap AMPL pools for V3 in candidate pools

src/providers/v2/subgraph-provider.ts
Allow VIRTUAL/GAME pool for V2 on Base subgraph pool filtering.
=> fix(subgraph): include VIRTUAL/GAME pool in V2 Base subgraph

src/providers/v2/subgraph-provider.ts, test/unit/providers/v2/subgraph-provider.test.ts
Allows all VIRTUAL/* pools in V2 Base subgraph until our subgraph is re-indexed
=> fix(subgraph): include all VIRTUAL/* pools in V2 Base subgraph

package-lock.json, package.json
bump sor to 4.8.4 to include https://github.com/Uniswap/smart-order-router/pull/773
=> chore: bump sor to 4.8.4 - fix(subgraph): include all VIRTUAL/* poolsin V2 Base subgraph

src/routers/alpha-router/gas-models/tick-based-heuristic-gas-model.ts, test/integ/routers/alpha-router/alpha-router.integration.test.ts
Addresses bug where we use bad synthetic gas estimate to calculate gas.
=> fix: Use syntheticGasCostInTermsOfQuoteToken only if within 30% of gasCostInTermsOfQuoteToken

src/providers/tenderly-simulation-provider.ts
Bug fix
Tenderly node block can fall behind RPC node block, hence node simulation failed with "not found".
We pass in latest for tenderly node simulation.
=> fix: pass latest to tenderly node

package-lock.json, package.json, src/providers/simulation-provider.ts, src/providers/tenderly-simulation-provider.ts, src/routers/alpha-router/gas-models/tick-based-heuristic-gas-model.ts, src/util/tenderlySimulationErrorBreakDown.ts, test/unit/util/tenderlySimulationErrorBreakDown.test.ts
feature
we don't break down the concrete tenderly simulation onchain revert error
We first determine whether the onchain revert might be due to slippage. there's a possibility it could also be insufficient liquidity. but for now we just return slippage too low
looking into adding tests, probably unit tests
=> chore: bump sor to 4.8.7 - feat: tenderly sim status SlippageTooLow

package-lock.json, package.json, src/providers/tenderly-simulation-provider.ts, test/integ/routers/alpha-router/alpha-router.integration.test.ts
feature
tenderly still on API for many L2s
migrate them to tenderly
=> chore: bump sor to 4.9.0 - feat: migrate all other L2s tenderly sim from API to node

package-lock.json, package.json, src/providers/tenderly-simulation-provider.ts
Bug fix
arbitrum had wrong tenderly node endpoint https://arbitrum-one.gateway.tenderly.co/${tenderlyNodeApiKey}
fix to have right tenderly node endpoint https://arbitrum.gateway.tenderly.co/${tenderlyNodeApiKey}
Tenderly didn't spot https://arbitrum-one.gateway.tenderly.co/${tenderlyNodeApiKey} was wrong when I was confirming with them https://uniswapteam.slack.com/archives/C01KV681S5C/p1733976476351119
=> fix: arb tenderly node endpoint

src/providers/tenderly-simulation-provider.ts, src/providers/token-provider.ts, src/util/tenderlySimulationErrorBreakDown.ts, test/unit/util/tenderlySimulationErrorBreakDown.test.ts
Bug fix
Sometimes slippage in virtual trading appears in the form in InsufficientToken in the universal router level
If tokenIn or tokenOut is $VIRTUAL, map InsufficientToken to SlippageTooLow 
this might not be due to slippage too low in the exact out scenario
=> fix: map virtual swap InsufficientToken as SlippageTooLow

package-lock.json, package.json, src/util/chains.ts
Bug fix
routing-api release pipeline failed:
> Error: Unknown chain id: 41454
at ID_TO_NETWORK_NAME (/codebuild/output/src1403594110/src/node_modules/@uniswap/smart-order-router/src/util/chains.ts:340:13)
at /codebuild/output/src1403594110/src/bin/stacks/routing-dashboard-stack.ts:113:78
at Array.map (<anonymous>)
at /codebuild/output/src1403594110/src/bin/stacks/routing-dashboard-stack.ts:108:27
at arrayMap (/codebuild/output/src1403594110/src/node_modules/lodash/lodash.js:653:23)
at map (/codebuild/output/src1403594110/src/node_modules/lodash/lodash.js:9622:14)
at Function.flatMap …
=> chore: bump sor to 4.10.1 - fix: ID_TO_NETWORK_NAME add unichain and monad testnet

package-lock.json, package.json
Include https://github.com/Uniswap/smart-order-router/pull/793
=> chore: bump sor to 4.14.0 - includes base sepolia + monad testnet

package-lock.json, package.json, src/providers/token-provider.ts
chore
we don't know which token had non-null terminator runtime error
log it so that we know
=> chore: bump sor to 4.14.1 - add bytes32 non-null terminator logging

package-lock.json, package.json, src/providers/token-provider.ts
bug fix
we know token symbol 0x0000000000000000000000000000000000000000000000000000000000000020, but we don't know token address.
log token address.
=> chore: bump sor to 4.14.2 - add bytes32 non-null terminator token address logging

package-lock.json, package.json, src/providers/tenderly-simulation-provider.ts
Bug fix
tenderly doesn't support monad testnet
bypass tenderly for monad testnt
=> fix: bump sor to 4.14.3 - fix: tenderly doesn't support monad testnet

package-lock.json, package.json, src/routers/alpha-router/alpha-router.ts, test/unit/routers/alpha-router/alpha-router.test.ts
- **What kind of change does this PR introduce?** 
Bug fix
- **What is the current behavior?**
Cached routes are still used when intent.caching
- **What is the new behavior?**
Don't use cachedRoutes if intent.caching
Start with `1%` experiment to validate and measure rpc/latency increase
=> fix: don't use cachedRoutes if intent.caching (1% experiment)

package-lock.json, package.json, src/routers/alpha-router/alpha-router.ts, src/routers/alpha-router/functions/get-candidate-pools.ts, src/util/pool.ts, src/util/serializeRouteIds.ts
chore
we dont know how often cached routes change
we log metrics to know how often cached routes change
we also log the chainId, as well as pair. we dont have the trading amount yet, because theres way too many fanouts.
Tested in routing-api, I can see:
- query string param cachedRoutesRouteIds
- cachedRoutesNotChanged metrics
=> chore: bump sor to 4.20.4 - log cached routes change metrics

package-lock.json, package.json, src/providers/on-chain-quote-provider.ts, src/routers/alpha-router/alpha-router.ts, src/util/chains.ts
Bug fix
We use wrong mixed quoter ABI on most chains, except for L1
We need to use mixed quoter V2 ABI on most chains, because we never deployed mixed quoter V1 on most chains.
=> fix: use v2 mixed quoter ABI for most chains

package-lock.json, package.json, src/providers/on-chain-quote-provider.ts
Bug fix
in beta pipeline, seeing
> [QuoteFetchError] Attempt 3. Unknown error from provider: types/values length mismatch (count={"types":3,"values":2}, value={"types":[{"name":"path","type":"bytes","indexed":null,"components":null,"arrayLength":null,"arrayChildren":null,"baseType":"bytes","_isParamType":true},{"name":"param","type":"tuple","indexed":null,"components":[{"name":"nonEncodableData","type":"tuple[]","indexed":null,"components":[{"name":"hookData","type":"bytes","indexed":null,"components":null,"arrayLength":null,"arrayChildren":null,"baseType":"bytes","_isParamType":true}],
this is because the mixed route doesn;t …
=> fix: mixed quoter types/values length mismatch

package-lock.json, package.json, src/routers/alpha-router/quoters/mixed-quoter.ts, src/util/mixedRouteFilterOutV4Pools.ts, src/util/routes.ts, test/unit/util/mixedRouteFilterOutV4Pools.test.ts
Bug fix
we return the mixed route that contains the v4 pool, where UR v1.2 was requested with protocols v2,v3
we need to make sure we filter out mixed route w/ v4 pool.
=> chore: bump sor to 4.20.9 - fix: UR v1.2 should have mixed route w/ v4 pool filtered out

package-lock.json, package.json, src/util/routes.ts
Bug fix
We do not wipe out cached routes in online lambda path.
We should wipe out cached routes in online lambda path.
i think its ok to have a perf hit in this case
because 1) theres not many mixed quote as best quote 2) for mixed route that contains v4 pool is even less 3) quote request with UR v1.2 header is even less
works on my local https://app.warp.dev/block/hiG5dT6jliXF7mOrzzwU0P
=> chore: bump sor to 4.20.10 - fix: remove optimisticCachedRoutes check in wiping cached routes

package-lock.json, package.json, src/providers/caching/route/route-caching-provider.ts, src/routers/alpha-router/alpha-router.ts, src/util/routes.ts
Bug fix
We dont have a way to control the percentage roll out w.r.t. wiping out cached routes during online routing lambda
We pass in the mixed route with UR v1_2 percent flag so that we can roll out the fix gradually.
This needs to be together with routing-api https://github.com/Uniswap/routing-api/pull/1065
=> chore: bump sor to 4.20.11 - fix: pass alphaRouterConfig to RouteCachingProvider for enableMixedRouteWithUR1_2Percent

package-lock.json, package.json, src/providers/caching/route/route-caching-provider.ts, src/routers/alpha-router/alpha-router.ts, src/routers/alpha-router/quoters/mixed-quoter.ts, src/util/mixedRouteFilterOutV4Pools.ts, src/util/routes.ts
Bug fix
We are passing in `enableMixedRouteWithUR1_2Percent`
We want to pass in `enableMixedRouteWithUR1_2` so that the percent is only computed once within routing-api
=> chore: bump sor to 4.20.12 - fix: enableMixedRouteWithUR1_2Percent to enableMixedRouteWithUR1_2

package-lock.json, package.json, src/routers/alpha-router/alpha-router.ts, test/unit/routers/alpha-router/alpha-router.test.ts
Bug fix
We bypass cache when NO_HOOKS
Desired is to bypass cache when HOOKS_INCLUSIVE
=> chore: bump sor to 4.21.2 - fix: bypass cache when HOOK_INCLUSIVE

package-lock.json, package.json, src/providers/v2/pool-provider.ts
Add v2 getPoools latency metrics
=> chore: add pool metrics on v2 getPools (+bump to 4.21.5)

package-lock.json, package.json, src/routers/alpha-router/quoters/v3-quoter.ts
Bug fix
we blocked ELMO v3 pool because ELMO is FOT, but ELMO v3 pool is coded to not take FOT tax.
allowlist ELMO v3 pool for quoting
=> chore: bump sor to 4.21.13 - fix: bypass v3 pool FOT check for  token

package-lock.json, package.json, src/providers/token-provider.ts, src/routers/alpha-router/functions/get-candidate-pools.ts, test/unit/routers/alpha-router/functions/get-candidate-pools.test.ts
Follow up on https://github.com/Uniswap/routing-api/pull/1109
Exclude direct v3 pool for EGGS
https://linear.app/uniswap/issue/CX-1005
=> fix: filter out direct v3 pool with rebase token breaking routing

package-lock.json, package.json, src/routers/alpha-router/functions/compute-all-routes.ts, test/unit/routers/alpha-router/functions/compute-all-routes.test.ts
Bug fix
We have invariant token error, because in v4, we can have circular route because of native & wrapped. e.g. ETH/OP -> ETH/OP-> ETH/opXEN
We make sure in case of v4, we track both native and wrapped as the same token being visited.
in case of mixed, we need to make sure we don't track both native and wrapped as the same token being visited.
=> chore: bump sor to 4.21.18 - fix: invariant token because of revisited v4 native pool eth/weth

package-lock.json, package.json, src/routers/alpha-router/functions/compute-all-routes.ts, test/unit/routers/alpha-router/functions/compute-all-routes.test.ts
Reverts Uniswap/smart-order-router#884 to support WETH hook natively: https://github.com/Uniswap/routing-api/pull/1130
=> Revert "chore: bump sor to 4.21.18 - fix: invariant token because of revisited v4 native pool eth/weth"

package-lock.json, package.json, src/providers/v4/euler-swap-hooks-subgraph-provider.ts
Bug fix
euler subgraph missing tickspacing, causing runtime error `Error: invalid BigNumber string (argument=\"value\", value=\"NaN\", code=INVALID_ARGUMENT, version=bignumber/5.7.0)`
in euler subgraph query, we need to query tickspacing as well
=> chore: bump sor to 4.22.1 - fix: euler subgraph query missing tickspacing siyujiang/route-539-support-euler-factory-hooks-routing

package-lock.json, package.json, src/providers/v4/pool-provider.ts, src/routers/alpha-router/functions/get-candidate-pools.ts
Bug fix
We re-compute pool id for dynamic fee pool, but with changing fee tier, pool id stays constant. so when we re-compute pool id, we got it wrong
we should always use the pool id from v4 subgraph.
aegis and renzo cannot route through
=> chore: bump sor to 4.22.2 - fix: dynamic fee pool id siyujiang/route-540-hook-aegis-debugging

src/providers/subgraph-provider.ts
Bug fix
zora has many creator pools and post pools. current subgraph cannot sync to tip. we need to migrate to new subgraph endpoint.
migrate to new subgraph endpoint. new endpoint needs bearer token, meanwhile old one doesn't
=> chore: bump sor to 4.22.13 - fix: support new gql endpoint for zora siyujiang/new-gql-endpointt

package-lock.json, package.json
We forgot to bump for https://github.com/Uniswap/smart-order-router/pull/909
=> chore: bump sor to 4.22.13

package-lock.json, package.json, src/routers/alpha-router/alpha-router.ts, src/routers/alpha-router/functions/get-candidate-pools.ts, test/unit/routers/alpha-router/functions/get-candidate-pools.test.ts
Bug fix
we don't have cross liquidity between v3 and v4. v3 zora/eth has 1.7mil tvl, needs to be used for connecting v4 zora creator pools.
we will have v3 and v4 cross liquidity
=> chore: bump sor to 4.22.17 - fix: cross liquidity between v3 and v4

package-lock.json, package.json, src/routers/alpha-router/alpha-router.ts, src/routers/alpha-router/functions/get-candidate-pools.ts, src/util/chains.ts, test/unit/routers/alpha-router/functions/get-candidate-pools.test.ts
Bug fix
cross liquidity v3 against v4 makes routing-api pipeline timing out on the mainnet
we decided to limit cross liquidity v3 against v4 only on base
v3 agaainst v4 is really for base jacob/eth against zora creator pool
=> chore: bump sor to 4.22.19 - fix: add per-chain feature flag to the mixed cross-liquidity v3 against v4
