Uniswap/smart-order-router

cli/base-command.ts, tsconfig.json
Builds the CLI to help from pushing breaking changes to CLI
=> include ./cli in build script

cli/commands/quote-to-ratio.ts, src/routers/alpha-router/alpha-router.ts, src/routers/router.ts, test/unit/routers/alpha-router/alpha-router.test.ts
There's a couple tweaks I'm making to smart-order-router. I will collect them here before doing any verison bumps.
(meant to make this draft)
=> return SwapToRatioResponse narrowing types + absoluteValue fix

src/providers/v3/subgraph-provider.ts
now that we have more than 5000 pools on v3 we should switch to pagination with the `id` field
=> replace skip with id pagination

cli/commands/quote-to-ratio.ts, package-lock.json, src/routers/alpha-router/alpha-router.ts, src/routers/legacy-router/legacy-router.ts, src/routers/router.ts, test/unit/routers/alpha-router/alpha-router.test.ts
=> Make calldata generation for swap and add optional

cli/commands/quote-to-ratio.ts, package-lock.json, package.json, src/routers/router.ts, test/unit/routers/alpha-router/alpha-router.test.ts
updatd router-sdk. + cli cleanup old variable names
=> Updated router sdk

src/providers/swap-router-provider.ts
=> Update router02 address in provider

README.md
- **What kind of change does this PR introduce?** 
Docs updated
=> Fix cli order for polygon not formatted properly

src/routers/alpha-router/alpha-router.ts
=> RouteToRatio edgecase fixes + better logging

README.md
=> Update readme for running integ tests

src/providers/index.ts
feature - exports the TokenValidatorProvider
=> feat: export TokenValidatorProvider

README.md
[Docs] Added section in README on how to add a new chain to SOR
=> [Docs] Added section in README on how to add a new chain to SOR

package-lock.json, package.json
=> Bump ts-node to 10.8.1

README.md
=> Add readme for node gas limit

package-lock.json, package.json
=> bump router-sdk to 1.2.0

src/providers/multicall-uniswap-provider.ts, src/routers/alpha-router/gas-models/v3/v3-heuristic-gas-model.ts, src/util/v3PoolHelper.ts, test/integ/routers/alpha-router/alpha-router.integration.test.ts
- **What kind of change does this PR introduce?**
- refactored: moved common methods into util file
=> Refactor v3 heuristic gas model

src/routers/alpha-router/alpha-router.ts, src/routers/alpha-router/gas-models/gas-model.ts, src/routers/alpha-router/gas-models/mixedRoute/mixed-route-heuristic-gas-model.ts, src/routers/alpha-router/gas-models/v2/v2-heuristic-gas-model.ts, src/routers/alpha-router/gas-models/v3/gas-costs.ts, src/routers/alpha-router/gas-models/v3/v3-heuristic-gas-model.ts, src/util/gas-factory-helpers.ts, test/unit/routers/alpha-router/alpha-router.test.ts
=> feat -> feat Eric/refactor gas factories

package-lock.json, test/integ/routers/alpha-router/alpha-router.integration.test.ts, test/unit/routers/alpha-router/alpha-router.test.ts
=> feat->feat Add mixedRoute unit tests

README.md, src/providers/index.ts, src/providers/v2/caching-pool-provider.ts, src/routers/alpha-router/alpha-router.ts, test/integ/routers/alpha-router/alpha-router.integration.test.ts
Should help reduce number of requests made to Infura
=> Add caching v2 pool provider by block

cli/base-command.ts, src/util/gas-factory-helpers.ts, src/util/routes.ts
=> Fix pool resolution for gas + routeString, cli fix

test/integ/routers/alpha-router/alpha-router.integration.test.ts
Since BSC has more liquidity now, we no longer have to special case BSC integ tests :)
=> fix: remove dedicated BSC test suite

package-lock.json, package.json
=> Version 3.11.5

package-lock.json, package.json
Upgrade token lists, required for downstream dependencies in routing-api repo.
=> fix: upgrade token list versions in package.json

src/providers/v2/subgraph-provider.ts
Bugfix: Updating the subgraph for v2
The current subgraph is failing to index due to a bad pool
fixing the new subgraph
=> Update v2 TheGraph subgraph

package.json
Releases https://github.com/Uniswap/smart-order-router/pull/282
=> bump sor version

src/providers/token-provider.ts, test/integ/routers/alpha-router/alpha-router.integration.test.ts
Bug fix
integ test doesn't compile.
integ test compiles
Follow up on ROUTE-41
=> fix: integ-test compiling error

src/routers/alpha-router/alpha-router.ts
feature
currently there's no configuration to control the usage of the cache, or overwrite it
The new configuration options allow us to control from routing api wether the cache will be used, and writte to, or not.
=> Add cached routes routing configs to control the usage of the cache

src/routers/alpha-router/alpha-router.ts
bug fix
`useCachedRoutes` will set the cacheMode to Darkmode
instead we want to just not read the cache, as this flag could be used to write into cache if we desire.
=> Update useCacheRoutes config

src/providers/on-chain-quote-provider.ts, src/providers/v2/pool-provider.ts
=> Add BatchSize metrics for onchainquoter and v2 get reserves

src/providers/on-chain-quote-provider.ts, src/providers/v2/pool-provider.ts
=> Add Batchsize metrics per chain

src/routers/alpha-router/functions/get-candidate-pools.ts, src/routers/alpha-router/quoters/mixed-quoter.ts, src/routers/alpha-router/quoters/v2-quoter.ts, src/routers/alpha-router/quoters/v3-quoter.ts
Debugging tools
Lack of metrics
New metrics used to track latencies
=> Add latency metrics for quoters

src/routers/alpha-router/functions/get-candidate-pools.ts, test/unit/routers/alpha-router/functions/get-candidate-pools.test.ts
=> Only add 4 direct swap pools if none was found

src/routers/alpha-router/functions/get-candidate-pools.ts
bug fix
Optimization:
We mostly have 3 code optimizations here:
1. The first thing we do on every loop is to break away from for loop if we have satisfied all conditions
2. I'm also changing some internal `.includes` calls by using a Set `.has` instead to go from O(n) to O(1) lookup
3. Additionally removed the parsing `Array.from` as much as possible doing iterables instead
=> More optimizations for candidate selection

src/routers/alpha-router/functions/get-candidate-pools.ts
bugfix
currently we accidentally introduced a bug where the pools do not get deduplicated
pools deduplication should work now
=> Dedup V2 SubgraphPools

src/routers/alpha-router/functions/get-candidate-pools.ts
=> Revert v3 candidate generation

src/routers/alpha-router/functions/get-candidate-pools.ts
new metric
no metrics
we track how many loops we do in each iteration before filling heuristics
=> Track how many loops we do in each subgraph iteration

src/routers/alpha-router/functions/get-candidate-pools.ts
Optimization
We currently might be able to find the TopByEthQuoteToken in the TopByBaseToken conditional, and then miss adding it to the array, hence iterating the whole list
Now we add it when we find that pool in the topByBase
=> TopByEthQuoteToken can be found in TopByBases

src/providers/caching-token-list-provider.ts, src/routers/alpha-router/functions/get-candidate-pools.ts
Refactor
Currently we are using an object literal as our data structure
Switching to a map and adding `has*` methods to look them up in constant time
=> Refactor CachingTokenListProvider

src/routers/alpha-router/functions/get-candidate-pools.ts
BugFix
TopByEthQuoteToken was not being selected due to not having a lowerCased address
Fixed
=> We need to look at the lowerCased address

src/routers/alpha-router/gas-models/v2/v2-heuristic-gas-model.ts
Optimization
2 async calls are made in sequence
parallelize these calls
=> Parallelize V2HeuristicsGasModel

src/routers/alpha-router/functions/get-candidate-pools.ts
Optimization
We currently iterate over the v2 second hops even if we dont have second hop tokens
Avoid doing this iteration if not needed
=> Avoid iterating over the second loops if we dont need to

src/routers/alpha-router/alpha-router.ts
Bug fix
We don't log the cached-routes top-level latencies at all. https://github.com/Uniswap/smart-order-router/pull/366
Fix cached routes telemetry.
=> fix cached routes metrics

src/providers/v2/caching-pool-provider.ts, src/providers/v3/caching-pool-provider.ts
=> Use Fire&Forget caching

src/routers/alpha-router/alpha-router.ts
BugFix
Metric issue
Metric fixed
=> Fix Cache Hit/Miss metrics

src/routers/alpha-router/alpha-router.ts
Revert Tapcompare change for comparing caching requests
=> Revert Tapcompare change for caching quotes

cli/commands/quote.ts, package-lock.json, package.json, src/providers/v2/quote-provider.ts, test/unit/providers/v2/quote-provider.test.ts
There is a bug in how we calculate FOT tax, but it is now fixed in v2-sdk and this should make this code cleaner
=> Update SOR to let v2-sdk handle the FOT calculation

src/routers/alpha-router/quoters/v2-quoter.ts
Realized that I put this for TODO but forgot to get back around to it.
It's not super elegant since the way we request for v2 quotes is a bit different than v3, as the gas model doesn't get created for each route/amount combination, but rather at the very beginning. However, we can assume that all input `amounts` are of the same token and that there is at least one element in the array so we can make it work.
=> fix: add eth wrap unwrap overhead for v2 routes

src/providers/eth-estimate-gas-provider.ts, src/providers/tenderly-simulation-provider.ts, test/integ/routers/alpha-router/alpha-router.integration.test.ts
=> fix: move addr override to within UNISVERSAL_ROUTER swaptype

package-lock.json, package.json
=> chore: 3.18.1

package-lock.json, package.json
=> chore: 3.18.2

src/providers/caching-gas-provider.ts, src/providers/eip-1559-gas-price-provider.ts, src/providers/eth-gas-station-info-gas-price-provider.ts, src/providers/gas-price-provider.ts, src/providers/legacy-gas-price-provider.ts, src/providers/on-chain-gas-price-provider.ts, src/providers/static-gas-price-provider.ts, src/routers/alpha-router/alpha-router.ts, test/unit/providers/gas-price-provider.test.ts
=> Fix: Gas price block aware

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/475
=> chore: bump to 3.21.0

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/482
=> chore: bump to 3.21.1

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/486
=> chore: bump to v3.22.0

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/485
=> chore: bump to 3.23.0

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/489
=> chore: bump to v3.24.0

src/util/chains.ts
- Remove tests from v2 support
- imports lint
=> Remove tests from V2 support

.github/workflows/tests.yml, test/integ/routers/alpha-router/alpha-router.integration.test.ts
Testing coverages
We don't have testing coverage against Sepolia. We regressed on Sepolia quote, but we didn't know.
We are adding testing coverages on Sepolia.
Sepolia doesn't have sufficient liquidities on non-USDC pools, so we are only enabling USDC-pools tests on Sepolia
=> chore: add sepolia tests

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/505
=> chore: bump to v3.24.5

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/507
=> chore: bump to v3.24.6

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/511
=> chore: bump to v3.25.0

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/513
=> chore: bump to v3.25.1

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/520
=> chore: bump to v3.26.1

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/510
=> chore: bump to v3.27.0

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/527
=> chore: bump to v3.27.1

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/529
=> chore: bump to v3.27.2

src/providers/token-fee-fetcher.ts
feature
We don't support FOT on L2s
We will support FOT on L2s
Please cross-check the contract addresses
=> feat: support fot on l2

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/531
=> chore: bump to v3.28.0

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/534
=> chore: bump to v3.28.1

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/536
=> chore: bump to v3.28.2

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/538 https://github.com/Uniswap/smart-order-router/pull/539
=> chore: bump to v3.28.3

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/542
=> chore: bump to v3.28.4

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/545
=> chore: bump to v3.28.5

src/providers/v2/subgraph-provider.ts, src/providers/v3/subgraph-provider.ts, test/integ/routers/alpha-router/alpha-router.integration.test.ts
In an effort to understand better how this cron job works and what's slowing it down, I'm adding some metrics here to understand it better.
=> chore: add metrics to subgraph provider

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/561
=> chore: bump to v3.28.10

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/563
=> chore: bump to v3.28.11

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/568
=> chore: bump to v3.28.13

package-lock.json, package.json
Release 
1. https://github.com/Uniswap/smart-order-router/pull/570
2. https://github.com/Uniswap/smart-order-router/pull/571
=> chore: bump to v3.29.0

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/584
=> chore: bump to v3.32.0

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/586
=> chore: bump to v3.33.0

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/588
=> chore: bump to v3.33.1

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/592
=> chore: bump to v3.34.0

.github/workflows/release.yml
I want to blame github copilot for this, but it's probably my fault for not making it - name instead of -name
=> fix(infra): set the yaml format for - name correctly

package-lock.json, package.json
=> chore: Bump version to 3.35.1

.github/workflows/release.yml
=> fix(infra): set the wrong vault name

package.json
Release https://github.com/Uniswap/smart-order-router/pull/604
=> chore: bump sor to 3.35.2

package-lock.json, package.json, src/routers/alpha-router/functions/best-swap-route.ts
=> log: gas token decimal diff

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/616
=> chore: bump sor to v3.35.8

package-lock.json
Reverts Uniswap/smart-order-router#622
=> chore(deps): revert update npm dependencies

src/providers/token-provider.ts, src/providers/v2/static-subgraph-provider.ts, src/providers/v3/static-subgraph-provider.ts, src/routers/alpha-router/functions/get-candidate-pools.ts
=> feat(routing): Set wstETH as a base token

src/routers/alpha-router/alpha-router.ts
Bug fix
We flipped the FOT fee metrics
Correct the reporting metrics
=> fix: FOT fee metrics reporting is flipped

package-lock.json, package.json
Includes the change to enable cross-protocol liquidity links
=> release: version 3.38.0

.github/workflows/release.yml
Adds provenance to our npm deploy. See https://docs.npmjs.com/generating-provenance-statements for more information
=> chore(infra): adds provenance

src/routers/alpha-router/alpha-router.ts, src/routers/alpha-router/gas-models/v3/v3-heuristic-gas-model.ts
Bug fix
We have no visibility into why 'division by zero' error
We are adding more loggings to understand why
=> chore: add 'division by zero' error logging

src/routers/alpha-router/gas-models/gas-model.ts, src/routers/alpha-router/gas-models/mixedRoute/mixed-route-heuristic-gas-model.ts, src/routers/alpha-router/gas-models/v3/v3-heuristic-gas-model.ts, src/util/methodParameters.ts, test/unit/routers/alpha-router/gas-models/mixed-route-gas-model.test.ts, test/unit/routers/alpha-router/gas-models/v3-gas-model.test.ts
Bug fix
We have incorrect tick crossing gas estimate logic
We are fixing tick crossing gas estimate logic. This is relevant for v3 and mixed (v3 part of mixed)
=> fix: ticks crossing gas estimate

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/680
=> chore: bump sor to 3.46.0

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/687
=> chore(sor): upgrade to 3.46.2

src/providers/token-provider.ts, src/util/addresses.ts, test/integ/routers/alpha-router/alpha-router.integration.test.ts, test/unit/providers/on-chain-quote-provider.test.ts
test
we are targeting old pool manager
we are updating the test against newly deployed pool manager
=> test: update v4 quoter deployed address on sepolia against new pool manager

cli/base-command.ts, cli/commands/quote.ts, src/util/protocols.ts
feature
CLI no v4 support
CLI v4 support
verified https://app.warp.dev/block/f7f3IPzDcucdOLx5X76AkY
=> feat: CLI V4 support

src/providers/subgraph-provider-with-fallback.ts, src/providers/subgraph-provider.ts, src/providers/v4/static-subgraph-provider.ts, src/providers/v4/subgraph-provider.ts, src/routers/alpha-router/alpha-router.ts, src/routers/alpha-router/functions/get-candidate-pools.ts, test/unit/routers/alpha-router/functions/get-candidate-pools.test.ts
feature
v4 subgraph doesn't support native currency v4 pool pulling
we will support v4 subgraph for native currency pool
=> feat: support native currency in getting candidate pools from v4 subgraph

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/707
=> chore: bump sor to 3.56.0

src/routers/alpha-router/functions/compute-all-routes.ts, src/routers/alpha-router/quoters/base-quoter.ts, src/routers/alpha-router/quoters/mixed-quoter.ts, src/routers/alpha-router/quoters/v2-quoter.ts, src/routers/alpha-router/quoters/v3-quoter.ts, src/routers/alpha-router/quoters/v4-quoter.ts, src/routers/router.ts, test/unit/routers/alpha-router/functions/compute-all-routes.test.ts
feature
mixed quoter doesn't support native currency quoting
mixed quoter to support native currency quoting.
=> feat: mixed quoter to support native curerncy quote

src/routers/alpha-router/alpha-router.ts, src/routers/alpha-router/entities/route-with-valid-quote.ts, src/routers/alpha-router/quoters/base-quoter.ts, src/routers/alpha-router/quoters/v4-quoter.ts, src/util/gas-factory-helpers.ts, test/unit/routers/alpha-router/alpha-router.test.ts
feature
if v4 quote token is native currency, we return wrapped token
if v4 quote token is native currency, we return native currency
this is the last part of https://github.com/Uniswap/smart-order-router/pull/715
=> feat: part 4 v4 quote token to quote currency

package-lock.json, package.json
bug fix
incorrect astrochain sepolia universal router deploy agian
bump ur-sdk again
=> fix: bump sor to 4.5.3 - bump ur-sdk to 4.3.2

src/providers/tenderly-simulation-provider.ts
feature
tenderly didnt supported astrochain
tenderly supports astrochain
=> feat: tenderly support astrochain sepolia now

package-lock.json, package.json
Release https://github.com/Uniswap/sdks/pull/178
this is for re-deployed v2 router on sepolia
=> chore: bump sor to 4.7.4 - bump sdk-core to 5.9.0

package-lock.json, package.json
releases https://github.com/Uniswap/smart-order-router/pull/757
=> chore: bump sor to 4.7.7 - chore: more metrics for routes/quotes fetched

package-lock.json, package.json
Bump sor to 4.8.2 - ship https://github.com/Uniswap/smart-order-router/pull/768
=> chore: bump sor to 4.8.2 - fix(subgraph): include VIRTUAL/GAME pool in V2 Base subgraph

src/providers/v2/subgraph-provider.ts, test/unit/providers/v2/subgraph-provider.test.ts
Allow top 20 VIRTUAL/* pool for V2 on Base subgraph pool filtering.
=> fix(subgraph): include top 20 VIRTUAL/* pools in V2 Base subgraph

package-lock.json, package.json
Bump sor to 4.8.8 - includes https://github.com/Uniswap/smart-order-router/pull/767
=> chore: bump sor to 4.8.8 - chore: add gas estimation quality metric

package-lock.json, package.json, src/util/addresses.ts
Bug fix
didn't add state view and v4 quoter addresses
add state view and v4 quoter addresses
=> fix: bump sor to 4.16.1 - fix: add stateview and v4 quoter addresses

package-lock.json, package.json
bump sor version to 4.17.0 - include https://github.com/Uniswap/smart-order-router/pull/766
=> chore: bump sor version to 4.17.0

package-lock.json, package.json, src/routers/alpha-router/alpha-router.ts
=> fix: cached routes undefined

package-lock.json, package.json, src/routers/alpha-router/alpha-router.ts, test/unit/routers/alpha-router/alpha-router.test.ts
=> fix(cache): skip cache if not all protocols are requested

test/unit/routers/alpha-router/functions/best-swap-route.test.ts
=> fix(test): update unit test for base swap route

package-lock.json, package.json, src/util/addresses.ts
=> chore: bump sor to 4.17.9 - base mixed quoter v1 address

.github/workflows/tests.yml, package-lock.json, package.json, src/providers/tenderly-simulation-provider.ts
=> fix(tenderly): add unichain node endpoint

package-lock.json, package.json, src/routers/alpha-router/alpha-router.ts
=> chore: bump sor to 4.20.13 - fix: enableDebug in alpha-router config

package.json, src/util/addresses.ts, src/util/chains.ts
@Nikita-Polyakov found a mismatch of WETH  address for the Arbitrum Sepolia network between this library and sdk-core. The correct address is taken from the sdk-core library.
To eliminate such mismatches, I used the WETH9 constant from the sdk-core library.
=> [Tech] merge WETH9 Arbitrum fix (#851)

package-lock.json, package.json, src/providers/v2/pool-provider.ts
Add latency metrics to identify latency section
=> chore: add more pool metrics on v2 getPools

package-lock.json, package.json, src/providers/v2/pool-provider.ts
Reverts Uniswap/smart-order-router#866
=> Revert "chore: add more pool metrics on v2 getPools"

package-lock.json, package.json, src/providers/subgraph-provider.ts
=> fix: base v3 subgraph filtering update

package-lock.json, package.json, src/providers/subgraph-provider.ts
=> fix: base v3 subgraph filtering update v2

package-lock.json, package.json, src/providers/subgraph-provider.ts
Apply the TVL fix to all chains for v3 subgraph filtering
=> fix: all v3 subgraph filtering update

package-lock.json, package.json
update package version for https://github.com/Uniswap/smart-order-router/pull/874
=> fix: update package version

package-lock.json, package.json, src/routers/alpha-router/alpha-router.ts, src/routers/router.ts, test/unit/routers/alpha-router/alpha-router.test.ts
=> chore: bump sor to 4.21.4 - fix: tenderly simulation during caching lambda

package-lock.json, package.json, src/providers/caching/route/route-caching-provider.ts, src/routers/alpha-router/alpha-router.ts
Passing swapOptions to trigger simulation
=> fix: ROUTE-467 Pass swapOptions

package-lock.json, package.json, src/routers/alpha-router/alpha-router.ts
Bug fix
We can't rollout the change on chain level (e.g. only enable 1 chain)
We can rollout the cache invalidation per chain
=> ROUTE-467 Rollout by chains

package-lock.json, package.json, src/providers/subgraph-provider.ts
Increase pagesize for base v4 subgraph as cron job times out due to too many calls.
=> fix: increase subgraph pageSize for Base v4 as well

package-lock.json, package.json, src/routers/alpha-router/alpha-router.ts
Bug fix
Mixed routing has bug in ur-sdk handling native wrap/unwrap.
ur-sdk bug has been fixed https://github.com/Uniswap/sdks/pull/378.
I verified both input and output wrap
https://github.com/Uniswap/sdks/pull/378#pullrequestreview-3080569450
https://github.com/Uniswap/sdks/pull/378#issuecomment-3155711474
=> chore: bump sor to 4.22.12 - fix: adopt ur-sdk fix on handling native wrap/unwrap during mixed routes

package-lock.json, package.json, src/providers/subgraph-provider.ts
=> fix(subgraph): increase base v3 pagesize

package-lock.json, package.json, src/providers/subgraph-provider.ts, src/providers/v3/subgraph-provider.ts, src/providers/v4/subgraph-provider.ts, test/integ/routers/alpha-router/alpha-router.integration.test.ts, test/unit/providers/v4/subgraph-provider.test.ts
Bug fix
We did not filter out zora low TVL pools
We will filter out low zora TVL pools
=> fix: filter low zora tvl pools
